### ISSUE TITLE
Evaluation children with names that are not identifiers do not work correctly

### ISSUE THREAD

**Issue by JeongPyoHam** [Microsoft/RTVS#1408]
```r
`123` <- 'hello'
```

123 appears in VE, and shows empty value, class, and type

**Comment by int19h** [comment]
In debugger, the value & type shows up, but the value cannot be edited; and if it's a collection, it cannot be expanded.

Probably just need to backtick-quote `DebugEvaluationResult.Name` if it's not a valid identifier token.

**Comment by int19h** [comment]
This presents a particular problem with dataframes, where members are column names, and are often not valid identifiers. See #1453 for an example.

**Comment by MikhailArkhipov** [comment]
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue

Internal debugger evaluation rtvs:::describe_children("as.environment(\".GlobalEnv\")$Bike_Rental_UCI_Dataset-2222$mnth", base::sys.frame(0), base::c('expression', 'kind', 'repr', 'repr.str', 'type', 'classes', 'length', 'slot_count', 'attr_count', 'dim', 'flags'), 20, 100) failed: ; 'Error in 2222$mnth : $ operator is invalid for atomic vectors
'

at Microsoft.R.Debugger.DebugSession.d__26.MoveNext()

at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolea......

Abort Retry Ignore
