### ISSUE TITLE
Assertion in grid when scrolling

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1429]
I was scrolling right when viewing `extra`:
```
url <- "https://cran.revolutionanalytics.com/web/packages/packages.rds"
tf <- file.path(tempdir(), "packages.rds")
download.file(url, destfile = tf, mode = "wb")
extra <- readRDS(tf)

```

and got this assertion:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
System.ArgumentException: Number of initializing data doesn't match with grid's dimensions

   at Microsoft.VisualStudio.R.Package.DataInspect.Grid`1..ctor(GridRange range, IList`1 list)

   at Microsoft.VisualStudio.R.Package.DataInspect.GridData.get_Grid()

   at Microsoft.VisualStudio.R.Package.DataInspect.VisualGridScroller.<DrawVisualsAsync>d__26.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

   at Microsoft.VisualStudio.R.Package.DataInspect.VisualGridScroller.<ExecuteCommandAsync>d__25.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSucc......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------

```

![image](https://cloud.githubusercontent.com/assets/1696845/14222294/e544997a-f823-11e5-94dd-2a89cc180bde.png)

**Comment by JeongPyoHam** [comment]
can't repro

**Comment by int19h** [comment]
I can still repro on the most current bits, using the above code, then docking the grid view in the editor tab well, and scrolling right by dragging the scrollbar, just about halfway through.

But you need to be running a Debug build, because the assert is `Debug.Fail`.

At the point where exception is thrown, the variables inside `Grid` ctor look like this:
```
-		range	{Microsoft.VisualStudio.R.Package.DataInspect.GridRange}	Microsoft.VisualStudio.R.Package.DataInspect.GridRange
-		Columns	[15,20)	Microsoft.VisualStudio.R.Package.DataInspect.Range
		Count	5	int
		Start	15	int
		_end	20	int
-		Rows	[0,11)	Microsoft.VisualStudio.R.Package.DataInspect.Range
		Count	11	int
		Start	0	int
		_end	11	int
-		list	Count = 28	System.Collections.Generic.IList<string> {System.Collections.Generic.List<string>}
		[0]	"NA"	string
		[1]	"NA"	string
		[2]	"NA"	string
		[3]	"NA"	string
		[4]	"NA"	string
		[5]	"NA"	string
		[6]	"NA"	string
		[7]	"NA"	string
		[8]	"NA"	string
		[9]	"NA"	string
		[10]	"NA"	string
		[11]	"Scott Fortmann-Roe                                                                               ..."	string
		[12]	"Gaurav Sood [aut, cre]                                                                           ..."	string
		[13]	"Csillery Katalin [aut],nLemaire Louisiane [aut],nFrancois Olivier [aut],nBlum Michael [aut, cre]"	string
		[14]	"Michael Thrun, Jorn Lotsch, Alfred Ultsch                                                        ..."	string
		[15]	"Csillery Katalin [aut],nLemaire Louisiane [aut],nFrancois Olivier [aut],nBlum Michael [aut, cre]"	string
		[16]	"Abhilash Gangadharan, Neha Rohatgi                                                               ..."	string
		[17]	"George Vega Yon <g.vegayon@gmail.com> [aut], Enyelbert MuÃ±oz <enyeldoc2011@gmail.com> [ctb]     ..."	string
		[18]	"M. Catherine Duryea, Andrew D. Kern, Robert M. Cox, and Ryan Calsbeek                            ..."	string
		[19]	"Jean-Michel Marin [aut, cre],nPierre Pudlo [aut],nChristian P. Robert [ctb],nArnaud Estoup [ctb]"	string
		[20]	"Matt Nunes [aut, cre],nDennis Prangle [aut]                                                      ..."	string
		[21]	"Kevin M. Middleton <middletonk@missouri.edu>, Randall Pruimn<rpruim@calvin.edu>                  ..."	string
		[22]	"NA                                                                                               ..."	string
		[23]	"person("	string
		[24]	"Sood"	string
		[25]	"gsood07@gmail.com"	string
		[26]	"aut"	string
		[27]	"cre"	string
```

Host log at the point of the first exception is attached.

[Microsoft.R.Host_REPL_20160411_110255_pid30068.txt](https://github.com/Microsoft/RTVS/files/213580/Microsoft.R.Host_REPL_20160411_110255_pid30068.txt)

**Comment by int19h** [comment]
I suspect that the problem here is that some cells in the data frame have complex values as person objects. E.g. from the log:
```
person(\\\"Gaurav\\\", \\\"Sood\\\", email = \\\"gsood07@gmail.com\\\", role = c(\\\"aut\\\", \\\"cre\\\"))
```

**Comment by JeongPyoHam** [comment]
resolved
