### ISSUE TITLE
VS crash: ObjectDisposedException for MarshalingWindowFrame

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1507]
Not clear if all of these are necessary, but the sequence was as follows:

1. Start VS; no RTVS toolwindows are visible (not even REPL).
2. Open Package Manager.
3. Open "Installed" tab, and search for "rtf" (package was already installed prior).
4. Click "Uninstall".
5. Open REPL window.

(I believe the key part here is trying to use Package Manager without having the REPL)

ObjectDisposedException for object name 'MarshalingWindowFrame' happens at this point. Stack doesn't seem to be particularly useful:
```
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr)
   at Microsoft.VisualStudio.R.Package.Shell.VisualComponentToolWindowAdapter`1.<>c__DisplayClass13_0.<Show>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by int19h** [comment]
Actually seems to be not related to packages at all. Just got it immediately after starting VS and opening REPL window, not even touching the package manager at all.

**Comment by MikhailArkhipov** [comment]
I've seen it too

**Comment by MikhailArkhipov** [comment]
Hmm, I think I made change to bring up repl on the PM start, looks like it got lost in the merge.

**Comment by MikhailArkhipov** [comment]
And actually, that change may be the trouble.

**Comment by AlexanderSher** [comment]
There is a reentrancy for `workflow.GetOrCreateVisualComponent`. I think I have a fix.
