### ISSUE TITLE
Crash in PlotContentProvider

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1519]
```
System events:
Time: 2016-04-08T14:40:45
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Threading.Tasks.TaskCanceledException
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.R.Package.Plots.PlotContentProvider+<ApplyNewSize>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.R.Package.Plots.PlotContentProvider+<RSession_Connected>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by huguesv** [comment]
May be due to the `SetCanceled` in `SilenceException` here:
https://github.com/Microsoft/RTVS/blob/master/src/Common/Core/Impl/Extensions/TaskExtensions.cs#L104

Most fire and forget operations in PlotContentProvider go through this:
```
        public static void DoNotWait(System.Threading.Tasks.Task task) {
            task.SilenceException<MessageTransportException>()
                .SilenceException<Microsoft.R.Host.Client.RException>()
                .DoNotWait();
        }
```
where DoNotWait does:
```
        public static async void DoNotWait(this Task task) {
            await task.SilenceException<OperationCanceledException>();
        }
```

So the goal is to ignore OperationCanceledException, but we end up turning that into TaskCanceledException which we don't catch.
