### ISSUE TITLE
Don't trace fail when connection with r-host dies

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1623]
This probably should be an assert.fail instead of trace.fail, since it's an expected scenario.
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Exception in RHost run loop:
System.OperationCanceledException: Connection closed by host.

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.R.Host.Client.WebSocketMessageTransport.<ReceiveAsync>d__13.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.R.Host.Client.RHost.<ReceiveMessageAsync>d__32.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.R.Host.Client.RHost.<RunLoop>d__46.MoveNext()......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by Marchen** [comment]
Upvote!

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/41fce45121d084c3bf007c8b18e699c95096ad69
