### ISSUE TITLE
Stop Debugging after Break crashes VS

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1697]
RTVS_2016-04-25.3

I was debugging, paused debugging, stopped debugging, then opened variable explorer (which was hidden).  VS crashed and this is from event viewer:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.R.Host.Client.REvaluationException
   at Microsoft.R.Host.Client.RExpressionEvaluatorExtensions.ThrowOnError(System.String, Microsoft.R.Host.Client.REvaluationResult)
   at Microsoft.R.Host.Client.RExpressionEvaluatorExtensions+<ExecuteAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Common.Core.TaskExtensions+<DoNotWait>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

I'll work on finding consistent repro and I'll send a frown.

**Comment by huguesv** [comment]
Logs here: \\pytools\r\Bugs\1697

**Comment by MikhailArkhipov** [comment]
Over to Pavel.

**Comment by huguesv** [comment]
I was able to repro a second time.
Open the project at \\pytools\r\Bugs\1697\rproject17
Attach debugger
Open TestData/dbg.R
Put a breakpoint in foo().
Source TestData/dbg.R
In REPL, type `foo(1,2)`
After it hits breakpoint, keep hitting F10.
Pause debugging.
Stop debugging.
Crash.

**Comment by int19h** [comment]
This is a bit of a unique case. Pause command issues a reentrant eval for `browser()` (it has to be reentrant to permit the prompt), and that eval remains active until the Browse> prompt that it causes is continued. If, instead, one does Stop Debugging - or e.g. cancels execution in the REPL - that causes this eval to fail. The code that triggers it uses `DoNotWait`, and doesn't swallow `RException` that it produces, so it leaks to the thread pool and produces a crash.

Other places that use `ExecuteAsync` or `EvaluateAsync<T>` do not use `DoNotWait`, but instead invoke it wrapped in `RunSynchronouslyOnUIThread`, which captures any exception and propagates it to the main thread, where it becomes a failing HRESULT when crossing the AD7 boundary, and is caught (and usually reported) by VS debugger code.
