### ISSUE TITLE
Exception formatting statement

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1706]
```
System.InvalidOperationException: Stack empty.
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at Microsoft.R.Core.Formatting.RFormatter.HandleBrace()
at Microsoft.R.Core.Formatting.RFormatter.AppendToken(Boolean leadingSpace, Boolean trailingSpace)  
at Microsoft.R.Core.Formatting.RFormatter.CloseFormattingScope()
at Microsoft.R.Core.Formatting.RFormatter.AppendNextToken()
at Microsoft.R.Core.Formatting.RFormatter.Format(String text)
at Microsoft.R.Editor.Formatting.RangeFormatter.FormatRangeExact
```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/c15056c2fa91884f38d5b672002d84598d3be5e1
