### ISSUE TITLE
Crash after pasting R code in R markdown code section

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1852]
Add new R Markdown file to your project.
Put this in your clipboard.
```
plot(hx, col = ifelse(abs(hx$breaks) < 1.669, 4, 2))
```

Select this line by clicking in the margin.
```
plot(cars)
```

Paste.
VS crashes.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.ThrowIfInvalid()
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.get_Start()
   at Microsoft.VisualStudio.Text.Editor.Implementation.TextViewLineCollection.FindTextViewLineIndexContainingBufferPosition(Microsoft.VisualStudio.Text.SnapshotPoint)
   at Microsoft.VisualStudio.Text.Editor.Implementation.TextViewLineCollection.GetTextViewLinesIntersectingSpan(Microsoft.VisualStudio.Text.SnapshotSpan)
   at Microsoft.VisualStudio.Text.Editor.Implementation.SolidColorBrushSelectionPainter.Update(Boolean)
   at Microsoft.VisualStudio.Text.Editor.Implementation.SolidColorBrushSelectionPainter.Activate()
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextSelection.set_IsActive(Boolean)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.OnLostKeyboardFocus(System.Object, System.Windows.Input.KeyboardFocusChangedEventArgs)
   at System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.KeyboardDevice.ChangeFocus(System.Windows.DependencyObject, Int32)
   at System.Windows.Input.KeyboardDevice.PostProcessInput(System.Object, System.Windows.Input.ProcessInputEventArgs)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(System.Windows.Input.ProcessInputEventHandler, System.Windows.Input.ProcessInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawKeyboardActions, Int32, Boolean, Boolean, Int32)
   at System.Windows.Interop.HwndKeyboardInputProvider.PossiblyDeactivate(IntPtr)
   at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)


```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/7f6b400551d23ea0a9c392ac34dfa0492c74708d

**Comment by MikhailArkhipov** [comment]
Still reproes

**Comment by MikhailArkhipov** [comment]
Specific to the very last line selected. Line selection via margin also selects trailing line break and replace damages projection boundary since ```[linebreak]'''``` is where the projection ends.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/82d5a2d02357aa6ce25563c5a302c5c8627f71cf
