### ISSUE TITLE
EvaluationWrapperTest.FormulaTest failure

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1887]
I'm using CRAN R 3.3.0

```
Test Name:	EvaluationWrapperTest.FormulaTest
Test FullName:	Microsoft.VisualStudio.R.Package.Test.DataInspect.EvaluationWrapperTest.FormulaTest
Test Source:	C:\Projects\huguesv\RTVS\src\Package\Test\DataInspect\EvaluationWrapperTest.cs : line 87
Test Outcome:	Failed
Test Duration:	0:00:03.623

Result StackTrace:	
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\CollectingAssertionStrategy.cs:line 50
   at FluentAssertions.Execution.AssertionScope.Dispose() in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 252
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\Core\Equivalency\EquivalencyValidator.cs:line 37
   at FluentAssertions.AssertionExtensions.ShouldBeEquivalentTo[T](T subject, Object expectation, Func`2 config, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Shared\AssertionExtensions.cs:line 687
   at Microsoft.VisualStudio.R.Package.Test.DataInspect.VariableRHostScript.AssertEvaluationWrapper(IRSessionDataObject rdo, VariableExpectation expectation) in C:\Projects\huguesv\RTVS\src\Package\Test\DataInspect\VariableRHostScript.cs:line 75
   at Microsoft.VisualStudio.R.Package.Test.DataInspect.VariableRHostScript.<EvaluateAndAssert>d__6.MoveNext() in C:\Projects\huguesv\RTVS\src\Package\Test\DataInspect\VariableRHostScript.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.R.Package.Test.DataInspect.EvaluationWrapperTest.<RunTest>d__29.MoveNext() in C:\Projects\huguesv\RTVS\src\Package\Test\DataInspect\EvaluationWrapperTest.cs:line 574
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
Expected member Value to be 
"Class 'formula' length 3 y ~ x1 * x2" with a length of 36, but 
"Class 'formula'  language y ~ x1 * x2" has a length of 37.
Expected member Value to be 
"Class 'formula' length 3 y ~ x1 * x2", but 
"Class 'formula'  language y ~ x1 * x2" differs near " la" (index 16).

With configuration:
- Use declared types and members
- Compare enums by value
- Try to match member by name
- Be strict about the order of items in byte arrays

```

**Comment by MikhailArkhipov** [comment]
3.2 makes

```Class 'formula' length 3 y ~ x1 * x2```

3.3+ yields

```Class 'formula'  language y ~ x1 * x2```

**Comment by huguesv** [comment]
I'll change it to conditionally validate against proper string based on the version of R.
