### ISSUE TITLE
New file does not appear in the project and AF when closing the project

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2060]
Not sure if this is truly needed, but this how I got there
Install SQL tools
Install AdventureWorks DB

1. Create R project
2. Open SQL Object Explorer (View -> ...)
3. Connect to local instance / AdventureWorks
4. Right click AdventureWorks -> New Query
5. SELECT * FROM Human...
6. Save SQL in the project folder

OBSERVED: file does not appear in the project (Show all does display it)
Close solution

![image](https://cloud.githubusercontent.com/assets/12820357/16740083/488f8aee-4752-11e6-8ec1-e91326d524d1.png)

```
'path' cannot be an empty string ("") or start with the null character.
Parameter name: path

   at Microsoft.Requires.NotNullOrEmpty(String value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.PathHelper.MakeRelative(String basePath, String path)
   at Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.Utilities.PathExtensions.ToShortRelativePath(IFileSystem fileSystem, String path, String rootFolder) in F:\RTVS\src\ProjectSystem\Impl\Utilities\PathExtensions.cs:line 14
   at Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.IO.MsBuildFileSystemWatcher.FileCreated.Apply() in F:\RTVS\src\ProjectSystem\Impl\IO\MsBuildFileSystemWatcher.FileCreated.cs:line 31

```

change appears to be OK

![image](https://cloud.githubusercontent.com/assets/12820357/16740165/9a4ec43a-4752-11e6-9f1e-dd2921fe5575.png)

**Comment by MikhailArkhipov** [comment]
[VsProjectFault_28cae22d-82a2-492e-a52c-c175d62947b9.failure.txt](https://github.com/Microsoft/RTVS/files/362078/VsProjectFault_28cae22d-82a2-492e-a52c-c175d62947b9.failure.txt)

**Comment by MikhailArkhipov** [comment]
[Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring_2016713_103231_pid4448.log.txt](https://github.com/Microsoft/RTVS/files/362080/Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring_2016713_103231_pid4448.log.txt)

**Comment by MikhailArkhipov** [comment]
```
 VerifyThrowNotSupportedItemChange(oldMetadata.ContainsKey(ConfigurationGeneralFile.LinkProperty) == metadata.ContainsKey(ConfigurationGeneralFile.LinkProperty));
                            if (oldMetadata.ContainsKey(ConfigurationGeneralFile.LinkProperty))
                            {
                                VerifyThrowNotSupportedItemChange(string.IsNullOrEmpty(oldMetadata[ConfigurationGeneralFile.LinkProperty]) == string.IsNullOrEmpty(metadata[ConfigurationGeneralFile.LinkProperty]));
                            }
 
```

**Comment by MikhailArkhipov** [comment]
Occasional race condition. IsFileAllowed throws

```
{"Could not find file '..."}
```
But second time succeeds

**Comment by MikhailArkhipov** [comment]
#2070

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/c48e807f47b950db2e459b4ca8b99ad761e69565
