### ISSUE TITLE
OutOfMemoryException in ReceiveMessageAsync

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2125]
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Exception in RHost run loop:
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

   at System.String.CtorCharArrayStartLength(Char[] value, Int32 startIndex, Int32 length)

   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)

   at Newtonsoft.Json.JsonTextReader.ParseValue()

   at Newtonsoft.Json.JsonTextReader.Read()

   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)

   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)

   at Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings)

   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)

   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)

   at Microsoft.R.Host.Client.RHost.<ReceiveMessageAsync>d__32.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

```

**Comment by int19h** [comment]
What is the context in which this appeared?

**Comment by MikhailArkhipov** [comment]
User says

```1. After some idle time this error message appeared.```

**Comment by int19h** [comment]
This requires logs to diagnose, to see what that JSON looked like.

**Comment by AlexanderSher** [comment]
Can it be related to #2079 ?

**Comment by int19h** [comment]
Ah, good point, the memory pressure can really come from anywhere, and just trip the wire here.

**Comment by karthiknadig** [comment]
Can we get a full-dump? we can examine the dump for signs of repetitive symbols. if the #2079 leak is the cause then we should see thousands of those symbols.

**Comment by int19h** [comment]
Without either logs or dumps, this isn't actionable, but there's good reason to suspect that #2079 is the root cause.
