### ISSUE TITLE
GetGlobalService called from a background thread.

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2126]
```
at Microsoft.R.Components.Extensions.CoreShellExtensions.AssertIsOnMainThread(ICoreShell coreShell, String memberName, String sourceFilePath, Int32 sourceLineNumber)

   at Microsoft.VisualStudio.R.Package.Shell.VsAppShell.GetGlobalService[T](Type type)

   at Microsoft.VisualStudio.R.Package.Debugger.DataTips.DataTipTextViewConnectionListener.SubjectBuffersConnected(IWpfTextView textView, ConnectionReason reason, Collection`1 subjectBuffers)

   at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.<>c__DisplayClass4_1.<.ctor>b__1()

   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

   at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager..ctor(IWpfTextView textView, ICollection`1 textViewConnectionListeners, GuardedOperations guardedOperations)
```

**Comment by MikhailArkhipov** [comment]
From user: ```When opened a non-R solution:```

**Comment by AlexanderSher** [comment]
Doesn't really matter - it is the same issue with accessing UI-thread dependent code in constructor of MEF-instantiated object.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/16bbfb33f3c03917ba44003ed507f46f3920cfac
