### ISSUE TITLE
Assertion in editor

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2153]
In the following code, delete the first single-quote on the fourth line, ie. before 2011.

```
n <- c(1, 2, 3)
s <- c('a', 'b', 'c')
b <- c(TRUE, NA, TRUE)
d <- c(as.Date('2011-12-31'), as.Date(NA), as.Date('2012-06-30'))
df <- data.frame(n, s, b, d)

structure(16496, class = "Date")
structure(NA_real_, class ="Date")
```

```

---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Children collection is sorted and yet no position to insert can be found



   at Microsoft.Languages.Core.Text.TextRangeCollection`1.AddSorted(T item) in C:\Projects\huguesv\rtvs\src\Languages\Core\Impl\Text\TextRangeCollection.cs:line 136

   at Microsoft.R.Core.AST.AstNode.AppendChild(IAstNode child) in C:\Projects\huguesv\rtvs\src\R\Core\Impl\AST\AstNode.cs:line 63

   at Microsoft.R.Core.AST.AstNode.set_Parent(IAstNode value) in C:\Projects\huguesv\rtvs\src\R\Core\Impl\AST\AstNode.cs:line 44

   at Microsoft.R.Core.AST.AstNode.AppendChild(IAstNode child) in C:\Projects\huguesv\rtvs\src\R\Core\Impl\AST\AstNode.cs:line 55

   at Microsoft.R.Core.AST.Expressions.Expression.MakeNode(ParseContext context) in C:\Projects\huguesv\rtvs\src\R\Core\Impl\AST\Expressions\ExpressionParser.cs:line 555

   at Microsoft.R.Core.AST.Expressions.Expression.ProcessHigherPrecendenceOperators(ParseContext context, IOperator currentOperator) in C:\Projects\huguesv\rtvs\src\R\Core\Impl\AST\Expressions\ExpressionParser.cs:lin......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```
![image](https://cloud.githubusercontent.com/assets/1696845/17449415/1e6e7218-5b0f-11e6-815e-ea3795e19424.png)

**Comment by MikhailArkhipov** [comment]
Minimal repro

```d <- c(as.Date('2011-12-31'), as.Date(NA), as.Date('2012-06-30'))```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/16bbfb33f3c03917ba44003ed507f46f3920cfac
