### ISSUE TITLE
CreateBlob_DisconnectedDuringCreate test fails with OutOfMemoryException

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2190]
BitConverter.ToString allocates 600Mb char array for 100Mb byte blob which causes the out of memory exception.

```
Test Name:         RSessionTest+Blobs.CreateBlob_DisconnectedDuringCreate
Test FullName:  Microsoft.R.Host.Client.Test.Session.RSessionTest+Blobs.CreateBlob_DisconnectedDuringCreate
Test Source:       D:\GitHub\RTVS\src\Host\Client\Test\Session\RSessionTest.Blobs.cs : line 59
Test Outcome:  Failed
Test Duration:    0:00:15.034
 
Result StackTrace:            
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at Microsoft.UnitTests.Core.FluentAssertions.AsyncAssertions.<ShouldThrowAsync>d__2`1.MoveNext() in D:\GitHub\RTVS\src\UnitTests\Core\Impl\FluentAssertions\AsyncAssertions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.R.Host.Client.Test.Session.RSessionTest.Blobs.<CreateBlob_DisconnectedDuringCreate>d__8.MoveNext() in D:\GitHub\RTVS\src\Host\Client\Test\Session\RSessionTest.Blobs.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:               
Expected Microsoft.R.Host.Client.Host.RHostDisconnectedException, but found {System.OutOfMemoryException with message "Exception of type 'System.OutOfMemoryException' was thrown."
     at System.BitConverter.ToString(Byte[] value, Int32 startIndex, Int32 length)
     at System.BitConverter.ToString(Byte[] value)
     at Microsoft.R.Host.Protocol.Message.ToString() in D:\GitHub\RTVS\src\Host\Protocol\Impl\Message.cs:line 93
     at Microsoft.R.Host.Client.RHost.<SendAsync>d__36.MoveNext() in D:\GitHub\RTVS\src\Host\Client\Impl\Host\RHost.cs:line 105
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
     at Microsoft.R.Host.Client.RHost.CreateBlobRequest.<SendAsync>d__1.MoveNext() in D:\GitHub\RTVS\src\Host\Client\Impl\Host\RHost.CreateBlobRequest.cs:line 19
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
     at Microsoft.R.Host.Client.RHost.<CreateBlobAsyncWorker>d__44.MoveNext() in D:\GitHub\RTVS\src\Host\Client\Impl\Host\RHost.cs:line 217
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
     at Microsoft.R.Host.Client.Session.RSession.<DoBlobServiceAsync>d__84`1.MoveNext() in D:\GitHub\RTVS\src\Host\Client\Impl\Session\RSession.cs:line 182
}.

```
1. Limit the size of the data that is being written to logs.
2. Add warning in logs for debug builds.

**Comment by MikhailArkhipov** [comment]
Part of #2191
