### ISSUE TITLE
Crash after adding/deleting in connections window

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2198]
Open connections window.
Click Add
Click Delete
Crash

```
Application: Microsoft.R.Host.Broker.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Timed out waiting for graceful shutdown.
Stack:
   at System.Environment.FailFast(System.String)
   at Microsoft.R.Host.Broker.Startup.Program+<>c+<<Exit>b__13_0>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Threading.Tasks.Task+DelayPromise.Complete()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

```

**Comment by int19h** [comment]
Were the connections different wrt to local/remote?

It looks like the broker was requested to shut down by regular means, but timed out waiting for all connections to close. I guess `FailFast` might have not been the best fallback for that in any case, but the real bug is why the connections didn't get closed within 10s... either something is not respecting the cancellation tokens, or >10s is actually reasonable for an ASP.NET app and the timeout needs to be adjusted.

**Comment by MikhailArkhipov** [comment]
No longer applies in the new UI
