### ISSUE TITLE
script.R disappeared from solution explorer, but is still on disk

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2215]
I'm connected to remote R.  See file explorer has script.R.

![image](https://cloud.githubusercontent.com/assets/1696845/17989372/af2a55a6-6ae1-11e6-81f3-3a0e9b9e22df.png)

I then closed and reopened solution, and got this error:
```
---------------------------
Microsoft Visual Studio
---------------------------
The project system has encountered an error.

 

R evaluation failed:

setwd('c:/Users/huvalo/Documents/Visual Studio 2015/Projects/rproject1/rproject1/')


Error in setwd("c:/Users/huvalo/Documents/Visual Studio 2015/Projects/rproject1/rproject1/") : 
  cannot change working directory




A diagnostic log has been written to the following location: "C:\Users\huvalo\AppData\Local\Temp\VsProjectFault_c45ee461-c671-43b6-858d-99efb2d13d5f.failure.txt".


---------------------------
OK   
---------------------------

```

Contents of above log:
```
=====================
8/25/2016 4:32:30 PM
Recoverable
Microsoft.R.Host.Client.REvaluationException: R evaluation failed:

setwd('c:/Users/huvalo/Documents/Visual Studio 2015/Projects/rproject1/rproject1/')


Error in setwd("c:/Users/huvalo/Documents/Visual Studio 2015/Projects/rproject1/rproject1/") : 
  cannot change working directory

   at Microsoft.R.Host.Client.RExpressionEvaluatorExtensions.ThrowOnError(String expression, REvaluationResult res)
   at Microsoft.R.Host.Client.RExpressionEvaluatorExtensions.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.R.Package.ProjectSystem.RProjectLoadHooks.<InitializeProjectFromDiskAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.AutoLoadMethodStateMachine.<<StartExecution>b__6_0>d.MoveNext()
===================

```

**Comment by MikhailArkhipov** [comment]
Looks like #2224
