### ISSUE TITLE
Broker can't detect R interpreters

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2255]
I have Microsoft R Client installed, but it can't see it.

```
Now listening on: http://0.0.0.0:5000
Application started. Press Ctrl+C to shut down.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HKUN7H0DKCP4" started.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 PUT http://ddhuvalo071:5000/sessions/REPL application/json; charset=utf-8 46
info: Odachi.AspNetCore.Authentication.Basic.BasicMiddleware[7]
      Basic was not authenticated. Failure message: No authorization header.
info: Odachi.AspNetCore.Authentication.Basic.BasicMiddleware[12]
      AuthenticationScheme: Basic was challenged.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 320.7822ms 401
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HKUN7H0DKCP4" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 PUT http://ddhuvalo071:5000/sessions/REPL application/json; charset=utf-8 46
info: Odachi.AspNetCore.Authentication.Basic.BasicMiddleware[3]
      HttpContext.User merged via AutomaticAuthentication from authenticationScheme: Basic.
dbug: Microsoft.AspNetCore.Routing.Tree.TreeRouter[1]
      Request successfully matched the route with name '' and template 'sessions/{id}'.
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action Microsoft.R.Host.Broker.Sessions.SessionsController.PutAsync (Microsoft.R.Host.Broker)
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful for user: huvalo.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Microsoft.R.Host.Broker.Sessions.SessionsController.PutAsync (Microsoft.R.Host.Broker) with arguments (REPL, Microsoft.R.Host.Protocol.SessionCreateRequest) - ModelState is Valid
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKUN7H0DKCP4": An unhandled exception was thrown by the application.
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.R.Host.Broker.Sessions.SessionsController.PutAsync(String id, SessionCreateRequest request)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 3932.114ms 200
```

**Comment by huguesv** [comment]
Here's the output if I specify path to interpreter in cmd line args:
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\R Tools for Visual Studio>Microsoft.R.Host.Broker --server.urls http://0.0.0.0:5000 --R:interpreters:1:basePath "C:\Program Files\Microsoft\R Client\R_SERVER" --security:secret foo
trce: Microsoft.R.Host.Broker.Interpreters.InterpreterManager[0]
      Auto-detecting R ...
warn: Microsoft.R.Host.Broker.Interpreters.InterpreterManager[0]
      No R interpreters auto-detected.
info: Microsoft.R.Host.Broker.Interpreters.InterpreterManager[0]
      1 interpreters configured:
      '1': 3.2.2 at "C:\Program Files\Microsoft\R Client\R_SERVER"
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[4]
      Hosting started
Hosting environment: Production
Content root path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\R Tools for Visual Studio
Now listening on: http://0.0.0.0:5000
Application started. Press Ctrl+C to shut down.


```

**Comment by MikhailArkhipov** [comment]
This means `RInstallation().GetCompatibleEngines()` returned nothing, but there was something in `_options.Interpreters` that looked valid.

**Comment by int19h** [comment]
For the second log, that is the expected behavior (and should work when you connect, provided that you also specify the interpreter ID as a fragment URL, e.g. http://localhost:5000#1). The first log is where there were no manually configured interpreters, and auto-detect didn't find any either.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/2e62ba12bb572cfadfafa58536ed607d89cc51f5
