### ISSUE TITLE
Exception hit while Testing connection

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2356]
---
## Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue

Microsoft.R.Host handshake expected:
#18446744073709551614# !End []

   at Microsoft.R.Host.Client.RHost.ProtocolError(FormattableString fs, Object message)
   at Microsoft.R.Host.Client.RHost.<RunWorker>d__50.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult res......

**Comment by AlexanderSher** [comment]
Do you have the rest of the stack trace?

**Comment by karthiknadig** [comment]
This is what I found in the TestBrokerConnectionAsync log:
[16-9-20_14-34-58]:[Response,depth=0]:#18446744073709551614# !End [] 
[16-9-20_14-39-56][ERROR]:Exception in RHost run loop:
                          System.IO.InvalidDataException: Microsoft.R.Host handshake expected:
                          #18446744073709551614# !End [] 
                             at Microsoft.R.Host.Client.RHost.<RunWorker>d__50.MoveNext()
                          --- End of stack trace from previous location where exception was thrown ---
                             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                             at Microsoft.R.Host.Client.RHost.<RunWorker>d__50.MoveNext()
                          --- End of stack trace from previous location where exception was thrown ---
                             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                             at Microsoft.R.Host.Client.RHost.<Run>d__51.MoveNext()

**Comment by int19h** [comment]
This is the fake `!End` message that is sent by broker when host crashes (the reason why host crashed is a separate issue, but I believe it to be the missing C++ runtime problem). The problem here is that VS expects to see a handshake first, and in this case all it gets is `!End` immediately.

Don't worry about it right now. This will be fixed as part of my host/session lifetime rework.

**Comment by MikhailArkhipov** [comment]
folding into #2176
