### ISSUE TITLE
Help on remote throws Http exception

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2359]
`?help`

- see "help server starting..."

`?plot`

An unhandled exception of type 'System.Net.HttpListenerException' occurred in mscorlib.dll

Additional information: An operation was attempted on a nonexistent network connection

```
   at System.Net.HttpResponseStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Common.Core.StreamExtensions.<CopyAndFlushAsync>d__0.MoveNext() in C:\RTVS\src\Common\Core\Impl\Extensions\StreamExtensions.cs:line 10
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.R.Host.Client.BrokerServices.RemoteUriWebService.<GetResponseAsync>d__4.MoveNext() in C:\RTVS\src\Host\Client\Impl\BrokerServices\RemoteUriWebService.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.R.Host.Client.BrokerServices.WebServer.<DoWorkAsync>d__22.MoveNext() in C:\RTVS\src\Host\Client\Impl\BrokerServices\WebServer.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Common.Core.TaskExtensions.<>c.<DoNotWaitThreadContinuation>b__6_0(Object s) in C:\RTVS\src\Common\Core\Impl\Extensions\TaskExtensions.cs:line 91
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by MikhailArkhipov** [comment]
Couldn't repro second time.

**Comment by karthiknadig** [comment]
I am not able to repro this.

**Comment by MikhailArkhipov** [comment]
I think question if we should be handling it.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/f4755eedde9c2354cf6fdf3ca5e92ccafb40472d
