### ISSUE TITLE
Null reference exception when plot window docked with documents and hidden

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2375]
Dock the plot window in document well.
Open an .R file such that the plot window document is no longer visible.
Issue a plot command.

Note: if you split the document well into 2 horizontal or vertical parts, with the .R file in one, plot in the other, it will work fine.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Exception in RHost run loop:
System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.R.Components.Plots.Implementation.WpfUnitsConversion.ToPixels(Visual visual, Size wpfSize) in C:\Projects\huguesv\RTVS\src\R\Components\Impl\Plots\Implementation\WpfUnitsConversion.cs:line 16

   at Microsoft.R.Components.Plots.Implementation.View.RPlotDeviceControl.GetPixelSizeAndResolution(Size wpfSize) in C:\Projects\huguesv\RTVS\src\R\Components\Impl\Plots\Implementation\View\RPlotDeviceControl.xaml.cs:line 48

   at Microsoft.R.Components.Plots.Implementation.View.RPlotDeviceControl.GetPlotWindowProperties() in C:\Projects\huguesv\RTVS\src\R\Components\Impl\Plots\Implementation\View\RPlotDeviceControl.xaml.cs:line 32

   at Microsoft.R.Components.Plots.Implementation.RPlotDeviceVisualComponent.GetDeviceProperties() in C:\Projects\huguesv\RTVS\src\R\Components\Impl\Plots\Implementation\RPlotDeviceVisualComponent.cs:line 126

   at Microsoft.R.Components.Plots.Implementation......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------

```

then you get:
```
R Host process is stopped. Click Reset to start a new one.Interactive Window is disconnected from R Session.
Try connecting to a remote machine in the Workspaces window or
click Reset to restart local R interpreter.
> 
```

**Comment by huguesv** [comment]
`var source = PresentationSource.FromVisual(visual);` returns `null`, `visual` input is not `null`. 
So next line crashes:
```
return (Size)source.CompositionTarget.TransformToDevice.Transform((Vector)wpfSize);
```

**Comment by jflam** [comment]
We can't ship 0.5 with this bug. It's way too easy to hit.

**Comment by MikhailArkhipov** [comment]
Yes, we should.
