### ISSUE TITLE
Test failure: TaskUtilitiesTest.WhenAllCancelOnFailure_NoCancellation

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2453]
Doesn't fail when you run just that test, but it fails if you run all tests in Microsoft.Common.Core.Test
```
Test Name:	TaskUtilitiesTest.WhenAllCancelOnFailure_NoCancellation
Test FullName:	Microsoft.Common.Core.Test.Tasks.TaskUtilitiesTest.WhenAllCancelOnFailure_NoCancellation
Test Source:	C:\Projects\huguesv\RTVS\src\Common\Core\Test\Tasks\TaskUtilitiesTest.cs : line 47
Test Outcome:	Failed
Test Duration:	0:00:00.219

Result StackTrace:	
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Numeric\NumericAssertions.cs:line 44
   at Microsoft.Common.Core.Test.Tasks.TaskUtilitiesTest.<WhenAllCancelOnFailure_NoCancellation>d__2.MoveNext() in C:\Projects\huguesv\RTVS\src\Common\Core\Test\Tasks\TaskUtilitiesTest.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	Expected value to be 2, but found 1.

```

**Comment by AlexanderSher** [comment]
Timeout increased
