### ISSUE TITLE
Test failure: Plot UI tests on high DPI

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2454]
The tests need to look at the test machine's DPI settings and use adjusted sizes rather than fixed sizes.

```
Test Name:	RPlotIntegrationUITest.ResizePlotError
Test FullName:	Microsoft.R.Components.Test.Plots.RPlotIntegrationUITest.ResizePlotError
Test Source:	C:\Projects\huguesv\RTVS\src\R\Components\Test\Plots\RPlotIntegrationUITest.cs : line 110
Test Outcome:	Failed
Test Duration:	0:00:03.144

Result StackTrace:	
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Numeric\NumericAssertions.cs:line 44
   at Microsoft.R.Components.Test.Plots.RPlotIntegrationUITest.<ResizePlotError>d__19.MoveNext() in C:\Projects\huguesv\RTVS\src\R\Components\Test\Plots\RPlotIntegrationUITest.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	Expected value to be 600, but found 750.

```

```
Test Name:	RPlotIntegrationUITest.ResizePlot
Test FullName:	Microsoft.R.Components.Test.Plots.RPlotIntegrationUITest.ResizePlot
Test Source:	C:\Projects\huguesv\RTVS\src\R\Components\Test\Plots\RPlotIntegrationUITest.cs : line 87
Test Outcome:	Failed
Test Duration:	0:00:02.257

Result StackTrace:	
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Numeric\NumericAssertions.cs:line 44
   at Microsoft.R.Components.Test.Plots.RPlotIntegrationUITest.<ResizePlot>d__18.MoveNext() in C:\Projects\huguesv\RTVS\src\R\Components\Test\Plots\RPlotIntegrationUITest.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	Expected value to be 600, but found 750.


```

**Comment by huguesv** [comment]
I think I need to add this to the test class to prevent from running in parallel: `[Collection(CollectionNames.NonParallel)]`
