### ISSUE TITLE
Test failures in Microsoft.R.Editor.Application.Test

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2456]
AutoFormatTest.R_AutoFormatIfNoScope
IntellisenseTest.R_CompletionFilesUserFolder
IntellisenseTest.R_DeclaredVariablesCompletion01
SmartIndentTest.R_SmartIndentTest02
SmartIndentTest.R_SmartIndentTest02

```
Test Name:	AutoFormatTest.R_AutoFormatIfNoScope
Test FullName:	Microsoft.R.Editor.Application.Test.Formatting.AutoFormatTest.R_AutoFormatIfNoScope
Test Source:	C:\Projects\huguesv\RTVS\src\R\Editor\Application.Test\Formatting\AutoFormatTest.cs : line 266
Test Outcome:	Failed
Test Duration:	0:00:13.192

Result StackTrace:	
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstLengthDifferences() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringEqualityValidator.cs:line 36
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 41
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 38
   at Microsoft.R.Editor.Application.Test.Formatting.AutoFormatTest.<R_AutoFormatIfNoScope>d__17.MoveNext() in C:\Projects\huguesv\RTVS\src\R\Editor\Application.Test\Formatting\AutoFormatTest.cs:line 275
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
Expected string to be 
"if (x > 1)\r\n    a" with a length of 17, but 
"if(x>1)\r\n    a" has a length of 14.
```

```
Test Name:	IntellisenseTest.R_CompletionFilesUserFolder
Test FullName:	Microsoft.R.Editor.Application.Test.Completion.IntellisenseTest.R_CompletionFilesUserFolder
Test Source:	C:\Projects\huguesv\RTVS\src\R\Editor\Application.Test\Completion\IntellisenseTest.cs : line 183
Test Outcome:	Failed
Test Duration:	0:00:18.664

Result StackTrace:	
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.NotBeNull(String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\ReferenceTypeAssertions.cs:line 53
   at Microsoft.R.Editor.Application.Test.Completion.IntellisenseTest.<R_CompletionFilesUserFolder>d__10.MoveNext() in C:\Projects\huguesv\RTVS\src\R\Editor\Application.Test\Completion\IntellisenseTest.cs:line 199
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	Expected object not to be <null>.
```

```
Test Name:	IntellisenseTest.R_DeclaredVariablesCompletion01
Test FullName:	Microsoft.R.Editor.Application.Test.Completion.IntellisenseTest.R_DeclaredVariablesCompletion01
Test Source:	C:\Projects\huguesv\RTVS\src\R\Editor\Application.Test\Completion\IntellisenseTest.cs : line 383
Test Outcome:	Failed
Test Duration:	0:00:06.862

Result StackTrace:	
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstLengthDifferences() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringEqualityValidator.cs:line 36
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 41
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 38
   at Microsoft.R.Editor.Application.Test.Completion.IntellisenseTest.<R_DeclaredVariablesCompletion01>d__19.MoveNext() in C:\Projects\huguesv\RTVS\src\R\Editor\Application.Test\Completion\IntellisenseTest.cs:line 406
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
Expected string to be 
"zzz111$y222" with a length of 11, but 
"zzz1$y2 " has a length of 8.
```

```
Test Name:	SmartIndentTest.R_SmartIndentTest02
Test FullName:	Microsoft.R.Editor.Application.Test.Formatting.SmartIndentTest.R_SmartIndentTest02
Test Source:	C:\Projects\huguesv\RTVS\src\R\Editor\Application.Test\Formatting\SmartIndentTest.cs : line 48
Test Outcome:	Failed
Test Duration:	0:00:14.451

Result StackTrace:	
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstLengthDifferences() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringEqualityValidator.cs:line 36
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 41
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 38
   at Microsoft.R.Editor.Application.Test.Formatting.SmartIndentTest.<R_SmartIndentTest02>d__5.MoveNext() in C:\Projects\huguesv\RTVS\src\R\Editor\Application.Test\Formatting\SmartIndentTest.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
Expected string to be 
"if (TRUE)\r\n    a\r\nx <- 1\r\n" with a length of 26, but 
"if(TRUE)\r\n    abbreviatex <- 1\r\n" has a length of 32.
```

```
Test Name:	SmartIndentTest.R_SmartIndentTest04
Test FullName:	Microsoft.R.Editor.Application.Test.Formatting.SmartIndentTest.R_SmartIndentTest04
Test Source:	C:\Projects\huguesv\RTVS\src\R\Editor\Application.Test\Formatting\SmartIndentTest.cs : line 89
Test Outcome:	Failed
Test Duration:	0:00:08.39

Result StackTrace:	
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstLengthDifferences() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringEqualityValidator.cs:line 36
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 41
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 38
   at Microsoft.R.Editor.Application.Test.Formatting.SmartIndentTest.<R_SmartIndentTest04>d__7.MoveNext() in C:\Projects\huguesv\RTVS\src\R\Editor\Application.Test\Formatting\SmartIndentTest.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	
Expected string to be 
"{\r\n    if (1)\r\n        a <- 1\r\n    else\r\n        b <- 2;\r\n}" with a length of 59, but 
"{\r\n    if(1)\r\n        a<-1\r\n    else \r\n        b <- 2;\r\n}" has a length of 57.
```

**Comment by MikhailArkhipov** [comment]
Autoformat and smart indent are the same issue as #2422, merging the fix soon.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/d438dc8cf54f4b468cdf5687d4de94cd7f754da2
