### ISSUE TITLE
Test failures in Microsoft.VisualStudio.R.Interactive.Test

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2457]
These 2 tests fail if you select all tests from the project and run.  They succeed if you run them individually.

```
Test Name:  VariableExplorerTest.SimpleDataTest
Test FullName:  Microsoft.VisualStudio.R.Interactive.Test.Data.VariableExplorerTest.SimpleDataTest
Test Source:    C:\Projects\huguesv\RTVS\src\Package\TestApp\Data\VariableExplorerTest.cs : line 35
Test Outcome:   Failed
Test Duration:  0:00:02.842

Result StackTrace:  
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Numeric\NumericAssertions.cs:line 44
   at Microsoft.Common.Core.Test.Utility.TestFiles.CompareToBaseLine(String baselinefilePath, String actual) in C:\Projects\huguesv\RTVS\src\Common\Core\Test\Utility\TestFiles.cs:line 28
   at Microsoft.VisualStudio.R.Interactive.Test.Utility.ViewTreeDump.CompareVisualTreesImplementation(DeployFilesFixture fixture, VisualTreeObject actual, String fileName) in C:\Projects\huguesv\RTVS\src\Package\TestApp\Utility\ViewTreeDump.cs:line 29
   at Microsoft.VisualStudio.R.Interactive.Test.Utility.ViewTreeDump.CompareVisualTrees(DeployFilesFixture fixture, VisualTreeObject actual, String fileName) in C:\Projects\huguesv\RTVS\src\Package\TestApp\Utility\ViewTreeDump.cs:line 17
   at Microsoft.VisualStudio.R.Interactive.Test.Data.VariableExplorerTest.<SimpleDataTest>d__3.MoveNext() in C:\Projects\huguesv\RTVS\src\Package\TestApp\Data\VariableExplorerTest.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message: 
Expected value to be 0 because there should be no difference at line 3053.
Expected:                                                                                              "Value": "x"
Actual:                                                                                              "Value": "grid.test"
Difference at position 105
, but found 3053.
```

```
Test Name:  VariableExplorerTest.SimpleFunctionTest
Test FullName:  Microsoft.VisualStudio.R.Interactive.Test.Data.VariableExplorerTest.SimpleFunctionTest
Test Source:    C:\Projects\huguesv\RTVS\src\Package\TestApp\Data\VariableExplorerTest.cs : line 48
Test Outcome:   Failed
Test Duration:  0:00:02.772

Result StackTrace:  
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Numeric\NumericAssertions.cs:line 44
   at Microsoft.Common.Core.Test.Utility.TestFiles.CompareToBaseLine(String baselinefilePath, String actual) in C:\Projects\huguesv\RTVS\src\Common\Core\Test\Utility\TestFiles.cs:line 28
   at Microsoft.VisualStudio.R.Interactive.Test.Utility.ViewTreeDump.CompareVisualTreesImplementation(DeployFilesFixture fixture, VisualTreeObject actual, String fileName) in C:\Projects\huguesv\RTVS\src\Package\TestApp\Utility\ViewTreeDump.cs:line 29
   at Microsoft.VisualStudio.R.Interactive.Test.Utility.ViewTreeDump.CompareVisualTrees(DeployFilesFixture fixture, VisualTreeObject actual, String fileName) in C:\Projects\huguesv\RTVS\src\Package\TestApp\Utility\ViewTreeDump.cs:line 17
   at Microsoft.VisualStudio.R.Interactive.Test.Data.VariableExplorerTest.<SimpleFunctionTest>d__4.MoveNext() in C:\Projects\huguesv\RTVS\src\Package\TestApp\Data\VariableExplorerTest.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message: 
Expected value to be 0 because there should be no difference at line 2919.
Expected:                                                                                              "Value": "Hidden"
Actual:                                                                                              "Value": "Visible"
Difference at position 105
, but found 2919.
```

**Comment by MikhailArkhipov** [comment]
Tests have been passing clean lately
