### ISSUE TITLE
Assert publishing rmd to pdf

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2512]
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
GetGlobalService at F:\A\_work\24\s\public\src\Package\Impl\Shell\VsAppShell.cs:161 was incorrectly called from a background thread.



   at Microsoft.Common.Core.Shell.CoreShellExtensions.AssertIsOnMainThread(ICoreShell coreShell, String memberName, String sourceFilePath, Int32 sourceLineNumber)

   at Microsoft.VisualStudio.R.Package.Shell.VsAppShell.GetGlobalService[T](Type type)

   at Microsoft.VisualStudio.R.Package.Shell.VsAppShell.ShowErrorMessage(String message)

   at Microsoft.VisualStudio.R.Package.Publishing.Commands.PreviewCommand.<>c__DisplayClass13_0.<<Invoke>b__0>d.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at Sy......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/21cc269b6ce0172d999bac543f125869873915a2

**Comment by MikhailArkhipov** [comment]
Found one more place to fix
