### ISSUE TITLE
Sort out settings load on package initialize

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2601]
VS does't like that

```
LegacySitePackage failed for package [RPackage]Source: 'Microsoft.VisualStudio.Shell.15.0'
Description: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.VisualStudio.Shell.DialogPage.SetPropertyValue(PropertyDescriptor descriptor, Object automationObject, Object value)
at Microsoft.VisualStudio.Shell.DialogPage.LoadSettingFromStorage(PropertyDescriptor prop)
at Microsoft.VisualStudio.Shell.DialogPage.LoadSettingsFromStorage()
at Microsoft.VisualStudio.R.Package.Options.R.RToolsOptionsPage.LoadSettingsFromStorage()
at Microsoft.VisualStudio.R.Package.Options.R.RToolsOptionsPage.LoadSettings()
at Microsoft.VisualStudio.R.Packages.R.RPackage.Initialize()
at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)
```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/0c596e001c0d28b61a1be02008ee7d6deb01d21e
