### ISSUE TITLE
Dev 15 RC package load failure

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2604]
```
LegacySitePackage failed for package [RPackage]Source: 'Microsoft.VisualStudio.Shell.15.0'
Description: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.VisualStudio.Shell.DialogPage.SetPropertyValue(PropertyDescriptor descriptor, Object automationObject, Object value)
at Microsoft.VisualStudio.Shell.DialogPage.LoadSettingFromStorage(PropertyDescriptor prop)
at Microsoft.VisualStudio.Shell.DialogPage.LoadSettingsFromStorage()
at Microsoft.VisualStudio.R.Package.Options.R.RToolsOptionsPage.LoadSettingsFromStorage()
at Microsoft.VisualStudio.R.Package.Options.R.RToolsOptionsPage.LoadSettings()
at Microsoft.VisualStudio.R.Packages.R.RPackage.Initialize()
at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)
```

**Comment by MikhailArkhipov** [comment]
#2601
