### ISSUE TITLE
Dev15: Loading settings through project package load fails

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2612]
```
   at Microsoft.VisualStudio.Shell.DialogPage.SetPropertyValue(PropertyDescriptor descriptor, Object automationObject, Object value)
   at Microsoft.VisualStudio.Shell.DialogPage.LoadSettingFromStorage(PropertyDescriptor prop)
   at Microsoft.VisualStudio.Shell.DialogPage.LoadSettingsFromStorage()
   at Microsoft.VisualStudio.R.Package.Options.R.RToolsOptionsPage.LoadSettingsFromStorage()
   at Microsoft.VisualStudio.R.Package.Options.R.RToolsOptionsPage.LoadSettings()
   at Microsoft.VisualStudio.R.Packages.R.RPackage.LoadSettings()
   at Microsoft.VisualStudio.R.Package.Shell.VsAppShell.EnsurePackageLoaded(Guid guidPackage)
   at Microsoft.VisualStudio.R.Package.ProjectSystem.RProjectLoadHooks.<InitializeProjectFromDiskAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.AutoLoadMethodStateMachine.<<StartExecution>b__8_0>d.MoveNext()
```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/57dfb8d52a0a1b5df62775af2c0bda5ae11d035b
