### ISSUE TITLE
Unable to run R 3.3.2

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2676]
CRAN 3.3.2

```
R Host process is stopped. Click "Reset" to start a new one.The following exception occurred during initialization of R session, and the session has been terminated:

Microsoft.R.Host.Client.Host.RHostDisconnectedException: Interactive Window is disconnected from R Session.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.R.Host.Client.Session.RSession.<AfterHostStarted>d__102.MoveNext() in F:\RTVS\src\Host\Client\Impl\Session\RSession.cs:line 385
```

**Comment by MikhailArkhipov** [comment]
Doesn't seem to be version specific. May be red herring since remote 3.3.1 is fine.

**Comment by MikhailArkhipov** [comment]
AppVerifier kills the host b/c

```
	<avrf:logSession TimeStarted="2016-11-04 : 16:41:23" PID="31812" Version="2">
		<avrf:logEntry Time="2016-11-04 : 16:41:30" LayerName="Handles" StopCode="0x303" Severity="Error">
			<avrf:message>NULL handle passed as parameter. A valid handle must be used.</avrf:message>
			<avrf:parameter1>0 - Not used.</avrf:parameter1>
			<avrf:parameter2>0 - Not used.</avrf:parameter2>
			<avrf:parameter3>0 - Not used.</avrf:parameter3>
			<avrf:parameter4>0 - Not used.</avrf:parameter4>
			<avrf:stackTrace>
				<avrf:trace>vfbasics!+7ff8455dfb08 ( @ 0)</avrf:trace>
				<avrf:trace>vfbasics!+7ff8455e0a6f ( @ 0)</avrf:trace>
				<avrf:trace>KERNELBASE!SetThreadPriority+12d ( @ 0)</avrf:trace>
				<avrf:trace>vfbasics!+7ff8455ded0e ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!TclpCreateCommandChannel+205 ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_MakeFileChannel+119 ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!TclpGetDefaultStdChannel+a0 ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_GetStdChannel+b1 ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_DeleteCloseHandler+177 ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_RegisterChannel+54 ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_ChannelTruncateProc+24fd ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_ListMathFuncs+78c ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_ExprObj+1be1 ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!TclObjInterpProcCore+df ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_ListMathFuncs+78c ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_ExprObj+1be1 ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!TclObjInterpProcCore+df ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_ListMathFuncs+78c ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_ExprObj+1be1 ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!TclObjInterpProcCore+df ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_ListMathFuncs+78c ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_ListMathFuncs+bca ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_ExprObj+1be1 ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!TclObjInterpProcCore+df ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_ListMathFuncs+78c ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_EvalEx+d5e ( @ 0)</avrf:trace>
				<avrf:trace>tcl85!Tcl_Eval+3c ( @ 0)</avrf:trace>
				<avrf:trace>tk85!TkCreateMainWindow+e7c ( @ 0)</avrf:trace>
				<avrf:trace>tk85!Tk_Init+1c ( @ 0)</avrf:trace>
				<avrf:trace>tcltk!tcltk_init+45 ( @ 0)</avrf:trace>
				<avrf:trace>tcltk!tcltk_start+5c ( @ 0)</avrf:trace>
				<avrf:trace>R!R_doDotCall+557c ( @ 0)</avrf:trace>
				<avrf:trace>R!do_Rprof+5d1f ( @ 0)</avrf:trace>
				<avrf:trace>R!do_Rprof+10dd1 ( @ 0)</avrf:trace>

```

**Comment by MikhailArkhipov** [comment]
Cleaning up backlog
