### ISSUE TITLE
EnsureInitialized must be called on the UI thread

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2701]
I see this message in the output window.

On my laptop, when this happens on debug build, it crashes VS and I see this in event viewer:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(System.String)
   at Microsoft.VisualStudio.R.Package.Shell.VsAppShell.EnsureInitialized()
   at Microsoft.VisualStudio.R.Package.Shell.VsAppShell.get_ExportProvider()
   at Microsoft.R.Support.Settings.RToolsSettings.get_Current()
   at Microsoft.R.Support.Help.IntelliSenseRSession+<CreateSessionAsync>d__14.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Support.Help.Packages.PackageIndex+<BuildIndexAsync>d__17.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Support.Help.Packages.PackageIndex+<BuildIndexAsync>d__16.MoveNext()
   at Microsoft.Common.Core.TaskExtensions.ReThrowTaskException(System.Object)
   at Microsoft.Common.Core.TaskExtensions.DoNotWait(System.Threading.Tasks.Task)
   at Microsoft.R.Support.Help.Packages.PackageIndex.OnBrokerStateChanged(System.Object, Microsoft.R.Host.Client.BrokerStateChangedEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at Microsoft.R.Host.Client.Session.RSessionProvider.OnBrokerConnected()
   at Microsoft.R.Host.Client.Session.RSessionProvider+<TrySwitchBrokerAsync>d__38.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Components.ConnectionManager.Implementation.ConnectionManager+<TrySwitchBrokerAsync>d__40.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Components.ConnectionManager.Implementation.ConnectionManager+<SwitchBrokerToLastConnection>d__50.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Components.ConnectionManager.Implementation.ConnectionManager+<CompleteInitializationAsync>d__30.MoveNext()
   at Microsoft.Common.Core.TaskExtensions.ReThrowTaskException(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

```

**Comment by karthiknadig** [comment]
After syncing to latest, I hit this every time while attempting to debug.

**Comment by MikhailArkhipov** [comment]
Folks, it takes less time to fix it that to file a bug. Move `ThrowIfNotOnUIThread` to GetInstance.

```
       public static void EnsureInitialized() {
            var instance = GetInstance();
            if (instance.MainThread == null) {
                instance.Initialize();
            }
        }
```

```
        private static VsAppShell GetInstance() {
            if (_instance != null) {
                return _instance;
            }

            ThreadHelper.ThrowIfNotOnUIThread();
            var componentModel = (IComponentModel)VsPackage.GetGlobalService(typeof(SComponentModel));
            var instance = (VsAppShell)componentModel.DefaultExportProvider.GetExportedValue<IApplicationShell>();

            return Interlocked.CompareExchange(ref _instance, instance, null) ?? instance;
        }
```

**Comment by int19h** [comment]
I'll take care of it.
