### ISSUE TITLE
Using IPv4 address instead of machine name fails with IOException

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2717]
using IPv4 address in work-spaces causes IOException Broker.

```
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      ConnectionFilter.OnConnection
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.<OnConnectionAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.<OnConnectionAsync>d__3.MoveNext()<---
```

**Comment by int19h** [comment]
I wonder if it's because the server also validates the SSL certificate it's configured to use against the hostname that the client told it expects? If so, that's probably by design.

**Comment by MikhailArkhipov** [comment]
Yeah I bet certificate is for name and not IP. I am actually not sure how SSL certificates work with IPs. Found

http://stackoverflow.com/questions/1095780/are-ssl-certificates-bound-to-the-servers-ip-address

_SSL certificates are bound to a 'common name', which is usually a fully qualified domain name but can be a wildcard name (eg. *.domain.com) or even an IP address, but it usually isn't._

_The SSL certificates are going to be bound to hostname rather than IP if they are setup in the standard way._ 

So it appears this is by design. May need to be documents. @jflam FYI

**Comment by int19h** [comment]
The name in the certificate is really just a string - it doesn't care if it's a domain, an IP, or something else. So when you generate it, you can simply specify the IP, and then that certificate will apply if someone is connecting by IP, since the SSL validation layer will simply match the host identifier (from the URL) against whatever is in the certificate.

**Comment by karthiknadig** [comment]
But is this the error that you get "remote party has closed the transport stream"? That is what threw me off.

**Comment by int19h** [comment]
Well, this is an error in the broker. I think what happens is that when they start the SSL negotiation, the client tries to validate certificate, and when it finds out that it doesn't match, we just drop the connection right there and then; and so this exception is how it surfaces on the broker side.

It may be that we can do something on the client to drop it in a more graceful manner, such that the server knows that it is done specifically because certificate is invalid.

**Comment by MikhailArkhipov** [comment]
As discussed, we'll document that https://github.com/Microsoft/RTVS-docs/issues/50
