### ISSUE TITLE
Still occasionally get package load failures

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2806]
```
An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\mikhaila\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml".

Exception details:
System.SystemException: System error.
   at Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid& packageGuid, Int32 reason, Guid& context)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetPackage()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent(
```

**Comment by MikhailArkhipov** [comment]
Launching second time went fine. Either some async operation or maybe VS was updating MEF in a background?

**Comment by AlexanderSher** [comment]
I have finished with #2801 (`CoreServises` isn't exported throw MEF anymore, and so the `ApplicationConstants`), probably that can help

**Comment by MikhailArkhipov** [comment]
Unable to create `Frame caption: Workspaces` when loading package. I guess something depends on the package being fully initialized.

**Comment by MikhailArkhipov** [comment]
Variant

```
LegacySitePackage failed for package [RPackage]Source: &apos;PresentationFramework&apos; Description: Could not load file or assembly &apos;Microsoft.R.Wpf, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies.
```

**Comment by MikhailArkhipov** [comment]
Specifically reproes if REPL is up before VS was closed. If VE or Workspaces was up then we get 'cannot construct tool windows content' if just REPL was up, we get 

```
System.Windows.Markup.XamlParseException: Could not load file or assembly &apos;Microsoft.R.Wpf, PublicKeyToken=b03f5f7f11d50a3a&apos; 
or one of its dependencies. The system cannot find the file specified. 

---&gt; System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.R.Wpf, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. 
The system cannot find the file specified.&#x000D;&#x000A;   
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   
at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   
at System.Reflection.Assembly.Load(AssemblyName assemblyRef)&#x000D;&#x000A;   
at System.Windows.Baml2006.Baml2006SchemaContext.ResolveAssembly(BamlAssembly bamlAssembly)&#x000D;&#x000A;   
at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlTypeToType(BamlType bamlType)&#x000D;&#x000A;   
at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType bamlType, Int16 typeId)&#x000D;&#x000A;   
at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16 typeId)&#x000D;&#x000A;   
at System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()&#x000D;&#x000A;   
at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()&#x000D;&#x000A;   
at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()&#x000D;&#x000A;   
at System.Windows.Baml2006.Baml2006Reader.Read()&#x000D;&#x000A;   
at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)&#x000D;&#x000A;   
at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)&#x000D;&#x000A;   
--- End of inner exception stack trace ---&#x000D;&#x000A;   

at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)&#x000D;&#x000A;   
at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)&#x000D;&#x000A;   
at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)&#x000D;&#x000A;   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)&#x000D;&#x000A;   
at Microsoft.R.Components.ConnectionManager.Implementation.View.ConnectionStatusBar.InitializeComponent()&#x000D;&#x000A;   
at Microsoft.R.Components.ConnectionManager.Implementation.ConnectionManager.&lt;CompleteInitializationAsync&gt;d__33.MoveNext()&#x000D;&#x000A;
--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;  
 
at Microsoft.Common.Core.TaskExtensions.ReThrowTaskException(Object state)&#x000D;&#x000A;   
at Microsoft.Common.Core.TaskExtensions.DoNotWait(Task task)&#x000D;&#x000A;   
at Microsoft.R.Components.ConnectionManager.Implementation.ConnectionManager..ctor(IStatusBar statusBar, IRSettings settings, IRInteractiveWorkflow interactiveWorkflow)&#x000D;&#x000A;   
at Microsoft.R.Components.ConnectionManager.Implementation.ConnectionManagerProvider.CreateConnectionManager(IRInteractiveWorkflow interactiveWorkflow)&#x000D;&#x000A;   
at Microsoft.R.Components.InteractiveWorkflow.Implementation.RInteractiveWorkflow..ctor(IConnectionManagerProvider connectionsProvider, IRHistoryProvider historyProvider, IRPackageManagerProvider packagesProvider, IRPlotManagerProvider plotsProvider, IActiveWpfTextViewTracker activeTextViewTracker, IDebuggerModeTracker debuggerModeTracker, ICoreShell coreShell, IRSettings settings)&#x000D;&#x000A;   
at Microsoft.VisualStudio.R.Package.Repl.VsRInteractiveWorkflowProvider.CreateRInteractiveWorkflow()&#x000D;&#x000A;   
at System.Lazy`1.CreateValue()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A; 
  
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   
at Microsoft.VisualStudio.R.Package.Repl.VsRInteractiveWorkflowProvider.GetOrCreate()&#x000D;&#x000A;   
at Microsoft.VisualStudio.R.Package.Repl.Editor.KeyProcessorProvider.GetAssociatedProcessor(IWpfTextView wpfTextView)&#x000D;&#x000A;   
at Microsoft.VisualStudio.Text.Editor.Implementation.InputController.&lt;UpdateKeyProcessors&gt;b__8_0(IKeyProcessorProvider p)&#x000D;&#x000A;   
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)
```

**Comment by MikhailArkhipov** [comment]
'Microsoft.R.Wpf' is not versioned.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/a14bf06b63f3141b11e0253446ce11434648a50c

**Comment by MikhailArkhipov** [comment]
Still reproes

**Comment by MikhailArkhipov** [comment]
This basically happens when editor tries to instantiate components when package was not loaded yet. Happens to classifier etc. This is by design. The problem is in

`KeyProcessorProvider(IRInteractiveWorkflowProvider provider)`

basically we cannot be importing anything package-dependent into code that editor may be instantiating in REPL.

**Comment by MikhailArkhipov** [comment]
Appears to be fixed now
