### ISSUE TITLE
Failure to set `AfterHostStarted` working directory stops RHost

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2843]
On my laptop I have (for some unknown reason) two user directories: `alsher` and `alsher.REDMOND`. The first one is not accessible without admin permissions and isn't really used. When I switch to local, RTVS peeks `alsher` as a user directory and since R has no access to it, `setwd` fails:
```
Error in setwd("C:/Users/alsher/Documents") : 
  cannot change working directory

   at Microsoft.R.Host.Client.RExpressionEvaluatorExtensions.ThrowOnError(String expression, REvaluationResult res) in D:\GitHub\RTVS\src\Host\Client\Impl\Definitions\IRExpressionEvaluator.cs:line 146
   at Microsoft.R.Host.Client.RExpressionEvaluatorExtensions.<ExecuteAsync>d__3.MoveNext() in D:\GitHub\RTVS\src\Host\Client\Impl\Definitions\IRExpressionEvaluator.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.R.Host.Client.Session.RSession.<AfterHostStarted>d__112.MoveNext() in D:\GitHub\RTVS\src\Host\Client\Impl\Session\RSession.cs:line 412
R Host process is stopped. Click "Reset" to start a new one.
```

**Comment by MikhailArkhipov** [comment]
I thought we added check for the directory existence. But I guess it also needs to handle access denied.

**Comment by MikhailArkhipov** [comment]
`setwd` should be fixed.
