### ISSUE TITLE
remote address needs https://

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2932]
if you dont add it, bad things happen... alex can repro too.

**Comment by AlexanderSher** [comment]
Here is the stack trace:
```cs
   at System.Net.Http.HttpClient.CheckBaseAddress(Uri baseAddress, String parameterName)
   at System.Net.Http.HttpClient.set_BaseAddress(Uri value)
   at Microsoft.R.Host.Client.Host.BrokerClient.CreateHttpClient(Uri baseAddress) in BrokerClient.cs: line 73
   at Microsoft.R.Host.Client.Host.RemoteBrokerClient..ctor(String name, BrokerConnectionInfo connectionInfo, ICoreServices services, IConsole console, CancellationToken cancellationToken) in RemoteBrokerClient.cs: line 38
   at Microsoft.R.Host.Client.Session.RSessionProvider.CreateBrokerClient(String name, BrokerConnectionInfo connectionInfo, CancellationToken cancellationToken) in RSessionProvider.cs: line 346
   at Microsoft.R.Host.Client.Session.RSessionProvider.<TrySwitchBrokerAsync>d__44.MoveNext() in RSessionProvider.cs: line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.R.Components.ConnectionManager.Implementation.ConnectionManager.<TrySwitchBrokerAsync>d__52.MoveNext() in ConnectionManager.cs: line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.R.Components.ConnectionManager.Implementation.ConnectionManager.<ConnectAsync>d__50.MoveNext() in ConnectionManager.cs: line 165
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run(Func`1 asyncMethod)
   at Microsoft.VisualStudio.R.Package.Shell.VsProgressDialog.Show(Func`2 method, String waitMessage, Int32 delayToShowDialogMs)
   at Microsoft.R.Components.ConnectionManager.Implementation.ViewModel.ConnectionManagerViewModel.Connect(IConnectionViewModel connection, Boolean connectToEdited) in ConnectionManagerViewModel.cs: line 296
   at Microsoft.R.Components.ConnectionManager.Implementation.View.ConnectionManagerControl.HandleConnect(RoutedEventArgs e, Boolean connectToEdited) in ConnectionManagerControl.xaml.cs: line 92
   at Microsoft.R.Components.ConnectionManager.Implementation.View.ConnectionManagerControl.ButtonConnect_Click(Object sender, RoutedEventArgs e) in ConnectionManagerControl.xaml.cs: line 37
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, ref Boolean handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, ref Boolean handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, ref Boolean handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by AlexanderSher** [comment]
Bug happens because `HttpClient` doesn't support any type of scheme except http and https.
I think we need to change logic in `ConnectionViewModel.GetCompletePath` to handle `host:port` pair as a URL without http or https.

**Comment by AlexanderSher** [comment]
@int19h , what do you think?

**Comment by AlexanderSher** [comment]
Currently we support only URL, cause we pass it directly to `HttpClient`, which supports only `http` and `https`:
```cs
    internal static bool IsHttpUri(Uri uri)  {
      string scheme = uri.Scheme;
      if (string.Compare("http", scheme, StringComparison.OrdinalIgnoreCase) != 0)
        return string.Compare("https", scheme, StringComparison.OrdinalIgnoreCase) == 0;
      return true;
    }
```

For a quick fix, we can check if `GetComponents(UriComponents.HostAndPort, UriFormat.UriEscaped)` returns an empty string, and try to parse the uri with "http://" at the beginning.

**Comment by int19h** [comment]
Didn't we have code in the UI layer that automatically corrected plain server names, or server:port pairs, to proper URLs, when you tab away from the textbox? @huguesv did that, if I remember correctly. Did we regress?

**Comment by AlexanderSher** [comment]
Not at all, this is how it was written:
```cs
        [InlineData("HOST", "https://host:5444")]
        [InlineData("host", "https://host:5444")]
        [InlineData("host:4000", "host:4000")] // host == scheme in this case and 4000 is actually a host name
        [InlineData("HOST:4000", "HOST:4000")] // host == scheme in this case and 4000 is actually a host name
        [InlineData("host#1234", "host#1234")]
        [InlineData("HOST#1234", "HOST#1234")]
        [InlineData("c:\\", "c:\\")]
        public void CompletePath(string original, string expected) {
            ConnectionViewModel.GetCompletePath(original).Should().Be(expected);
        }
```

**Comment by AlexanderSher** [comment]
Though comment to the `[InlineData("host:4000", "host:4000")]` is invalid. `4000` isn't a host name, such URI has no host or port, `4000` is part of the path. To make it a host, it should be `host://4000`

**Comment by int19h** [comment]
So basically it does autocorrect `host` to a proper URI, but not `host:port`. Looks like we just need to add the latter, and validate the scheme?

As I recall, it was not intended to imply that input like `host` or `host:4000` is a valid URI. It just happens to be a simplified form that's convenient for the users to enter. 

I think what we should do here is check for `://`. If it's present, parse it as URI. If it's not present, prepend `https://` and then parse as URI. After parsing, if port was not specified, set it to 5444, otherwise leave as is. If parsing failed, report error.

**Comment by MikhailArkhipov** [comment]
We should correct in the user-friendly way.

a) Protocol should not be required. If user enters it, we auto-correct to `https` i.e. `ftp://foo` -> `https://foo:5444`, and not 443.

**Comment by smortaz** [comment]
+1. This was the source of my connection issues.

**Comment by int19h** [comment]
Per above, we already autocorrect if port is not specified (i.e. `foo` becomes `https://foo:5444`). We should just extend the same autocorrection logic to the case where there is a port.

**Comment by MikhailArkhipov** [comment]
We also should replace anything that is not `https` with `https://` as well as handle `host:port` as `https://host:port` and not rely on `Uri.TryCreate` which is then using `host` as scheme name.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/fecbdbb4621d16e0727ffd3b2928503fde73c78e
