### ISSUE TITLE
NRE is markdown region highlighter

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2948]
From user logs
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.Markdown.Editor.Classification.CodeBackgroundTextAdornment.ShouldHighlightEntireLine(IWpfTextViewLine line)
at Microsoft.Markdown.Editor.Classification.CodeBackgroundTextAdornment.CreateVisuals(IWpfTextViewLine line)
at Microsoft.Markdown.Editor.Classification.CodeBackgroundTextAdornment.ProcessLine(ITextViewLine line)
at Microsoft.Markdown.Editor.Classification.CodeBackgroundTextAdornment.OnLayoutChanged(Object sender, TextViewLayoutChangedEventArgs e)
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/184e299a926b811d100edb3984dfe4835a880101
