### ISSUE TITLE
Attempt to connect to the same remote from another VS instance throws exception

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2963]
```
Microsoft R Open 3.3.1
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2016 Microsoft Corporation

Using the Intel MKL for parallel mathematical computing(using 4 cores).

Default CRAN mirror snapshot taken on 2016-07-01. See: https://mran.microsoft.com/.
R Host process is stopped. Click "Reset" to start a new one.
The following exception occurred during initialization of R session, and the session has been terminated:

Microsoft.R.Host.Client.Host.RHostDisconnectedException: RHost is stopped ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.R.Host.Client.RHost.<EvaluateAsync>d__46.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.R.Host.Client.RHost.<EvaluateAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.R.Host.Client.Session.RSession.<EvaluateAsync>d__91.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.R.Host.Client.RExpressionEvaluatorExtensions.<EvaluateAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.R.Host.Client.Session.RSession.<AfterHostStarted>d__113.MoveNext()
RHost is stopped
Click "Reset" to start a new session.
⚹>
```

**Comment by int19h** [comment]
Does this throw in the instance that was already connected, or in the one that's performing the connection?

**Comment by MikhailArkhipov** [comment]
With my changes I see

![image](https://cloud.githubusercontent.com/assets/12820357/21662909/a9b27adc-d291-11e6-9253-d4d327a861ff.png)

**Comment by MikhailArkhipov** [comment]
However, need to check what happens when I connect to the same machine as same user but select different interpreters

**Comment by MikhailArkhipov** [comment]
If I click reset on the terminated session, again, we behave correctly:

![image](https://cloud.githubusercontent.com/assets/12820357/21662973/033f5804-d292-11e6-82e1-506ee683bcf1.png)

**Comment by MikhailArkhipov** [comment]
Connecting to 2 different Rs works fine

![image](https://cloud.githubusercontent.com/assets/12820357/21663018/570b1766-d292-11e6-8ed5-a19f9c8ec8c9.png)

**Comment by int19h** [comment]
I think interpreter is part of the session hash that we use for IDs now? So on the broker, they're basically different session names, running concurrently.

**Comment by MikhailArkhipov** [comment]
The exception only happens if one tries to connect to the same remote concurrently from two instances. It looks like host is stopped while RTVS-related initialization code was still running (i.e. `AfterHostStarted` that is between `connected` and `interactive`).

The message is excessive, we already output that the host is stopped. I will `#if DEBUG` this output.

**Comment by smortaz** [comment]
btw the msg "Host is stopped" is quite meaningless to users.  we should
come up with something else.  the majority will have no clue about any
brokers, hosts, etc

in fact "host is stopped" is confusing enough (because "host" can also mean
remote host machine), that people might think the remote machine has
stopped responding.

**Comment by MikhailArkhipov** [comment]
We can adjust some wording to say, 'R Session is stopped', but if user doesn't understand how things work at least at the high level, they won't be helpful no matter what they say. They can be helpful for us or for the admin to diagnose issues.

'Stopped session' also may mean remote is disconnected. Compare to browser 'site has stopped responding': was that site, DNS, router or the network went down?

**Comment by smortaz** [comment]
ok.  how about:

R session is currently stopped
Remote R session is currently stopped

as long as it's not

Host stopped.  that's too overloaded.

**Comment by MikhailArkhipov** [comment]
Yeah, I changed 'Host' to 'session'. There is no separate remote distinction. There is local and remote workspaces and sessions within them. Session itself and related code doesn't necessarily know it is remote and hence cannot produce separate error messages.

**Comment by smortaz** [comment]
+1

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/1e553fc7584a9c6be107baf4d4e76debe5610218
