### ISSUE TITLE
Assert and sometimes hang when quitting VS after using locator function

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3011]
```
plot(euro)
locator()
```

Test 1 - close vs

result: assert then hang

Test 2 - click end locator then close vs

result: assert then everything is fine

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
EndLocatorMode at C:\Projects\huguesv\RTVS\src\R\Components\Impl\Plots\Implementation\ViewModel\RPlotDeviceViewModel.cs:154 was incorrectly called from a background thread.



   at Microsoft.Common.Core.Shell.CoreShellExtensions.AssertIsOnMainThread(ICoreShell coreShell, String memberName, String sourceFilePath, Int32 sourceLineNumber) in C:\Projects\huguesv\RTVS\src\Common\Core\Impl\Shell\CoreShellExtensions.cs:line 29

   at Microsoft.R.Components.Plots.Implementation.ViewModel.RPlotDeviceViewModel.EndLocatorMode() in C:\Projects\huguesv\RTVS\src\R\Components\Impl\Plots\Implementation\ViewModel\RPlotDeviceViewModel.cs:line 154

   at System.Threading.CancellationToken.ActionToActionObjShunt(Object obj)

   at System.Threading.CancellationCallbackInfo.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext execu......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by MikhailArkhipov** [comment]
This is b/c 
```
ct.Register(EndLocatorMode);
```
calls on bg thread. `_shell.DispatchOnUIThread` to the rescue

**Comment by huguesv** [comment]
Yes, I'm testing it right now.

**Comment by huguesv** [comment]
It still hangs when I close VS while in locator mode.  Main thread is here:

```
    internal class VsTaskService : ITaskService {
        public bool Wait(Task task, CancellationToken cancellationToken = default(CancellationToken), int ms = Timeout.Infinite) 
            => UIThreadReentrancyScope.WaitOnTaskComplete(task, cancellationToken, ms);
    }
```

called from `RSessionProvider.Dispose`:
```
            var sessions = GetSessions().ToList();
            var stopHostTasks = sessions.Select(session => session.StopHostAsync(false));
            try {
                _services.Tasks.Wait(Task.WhenAll(stopHostTasks));
            } catch (Exception ex) when (!ex.IsCriticalException()) { }

```

There's 3 tasks that it's waiting on, the REPL one is the one that doesn't complete.  In Tasks window, it shows its state as Waiting for Activation.

**Comment by MikhailArkhipov** [comment]
@AlexanderSher - can you comment? Need to get this resolved before EOW.

**Comment by AlexanderSher** [comment]
`StartLocatorModeAsync` last continuation needs to continue on UI thread, which is not available at VS shutdown. `RPlotDeviceViewModel.EndLocatorMode` should cancel `_locatorTcs` instead of completing it.

**Comment by huguesv** [comment]
That wasn't sufficient to make the host main loop unstuck.
That gave me an idea though, I made changes so that `StartLocatorModeAsync` never needs to switch to the main thread, and it appears to work fine.  PR coming.
