### ISSUE TITLE
Sometime package manager appears empty

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3217]
Switching between tabs populates it

![image](https://cloud.githubusercontent.com/assets/12820357/23182401/4474a692-f82d-11e6-807a-6a158e9e2bc5.png)

**Comment by AlexanderSher** [comment]
Any specific steps or conditions?

**Comment by MikhailArkhipov** [comment]
nope, just connected to local and opened it. Seen this periodically but not too often, looks like async issue. Trying to debug.

**Comment by MikhailArkhipov** [comment]
So the repro is

- make sure all windows except Workspaces is closed
- Start VS

You will get BP hit in `GetInstalledPackagesAsync`. But since there is no connection, I guess it ends with nothing.

- Open PM

Two BPs hit: `GetInstalledPackagesAsync` and then `GetAvailablePackagesAsync`. 

The window remains empty.

**Comment by MikhailArkhipov** [comment]
Interestingly enough, if I 

1. Open PM (with local R active)
2. Close VS
3. Start VS

PM window appears with 'loading' and then auto-closes. B/c there is no R connected?

**Comment by MikhailArkhipov** [comment]
There are 2 concurrent executions of `GetPackagesAsync` on the same session since `GetInstalledPackagesAsync` and `GetAvailablePackagesAsync` operate concurrently.

**Comment by AlexanderSher** [comment]
That is fine, we can get into this state by switching tabs fast enough

**Comment by MikhailArkhipov** [comment]
But is it OK to concurrently start and initialize sessions?

```
                await _session.EnsureHostStartedAsync(new RHostStartupInfo(), null, cancellationToken: cancellationToken);
                await _session.SetVsCranSelectionAsync(CranMirrorList.UrlFromName(_settings.CranMirror), cancellationToken);
                await _session.SetCodePageAsync(_settings.RCodePage, cancellationToken);
```

**Comment by AlexanderSher** [comment]
Session is initialized after `EnsureHostStartedAsync` already.
`SetVsCranSelectionAsync` and `SetCodePageAsync` are called to update code page and CRAN mirror from REPL session.

**Comment by MikhailArkhipov** [comment]
`GetInstalledPackagesAsync` is not called at all when this reproes

**Comment by AlexanderSher** [comment]
`LoadInstalledAndLoadedPackagesAsync` fails with the following error:
```
Error: R evaluation failed:

rtvs:::packages.installed()

Error in loadNamespace(name) : 
  cyclic namespace dependency detected when loading `tools', already loading `tools'
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
```
```cs
   at Microsoft.R.Components.PackageManager.Implementation.RPackageManager.<WrapRException>d__39`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.R.Components.PackageManager.Implementation.RPackageManager.<GetPackagesAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.R.Components.PackageManager.Implementation.RPackageManager.<GetInstalledPackagesAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.R.Components.PackageManager.Implementation.ViewModel.RPackageManagerViewModel.<LoadInstalledAndLoadedPackagesAsync>d__65.MoveNext()
```

**Comment by AlexanderSher** [comment]
`LoadInstalledAndLoadedPackagesAsync` fails and creates an error message. Then `ReloadLoadedPackagesAsync` is called several times (it is called every time REPL `RSession` fires `Mutated` event), so eventually it removes error message that was set by `LoadInstalledAndLoadedPackagesAsync`.

**Comment by MikhailArkhipov** [comment]
We can filter out `REvaluationException`, it has no value to the user
