### ISSUE TITLE
VS2015 crashing after R tools update

### ISSUE THREAD

**Issue by arvindravish** [Microsoft/RTVS#3249]
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.R.Host.Client.REvaluationException
   at Microsoft.R.Host.Client.RExpressionEvaluatorExtensions.ThrowOnError(System.String, Microsoft.R.Host.Client.REvaluationResult)
   at Microsoft.R.Host.Client.RExpressionEvaluatorExtensions+<ExecuteAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)
   at Microsoft.R.Host.Client.Session.RSession+<AfterHostStarted>d__113.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Host.Client.Session.RSession+<StartHostAsyncBackground>d__105.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Host.Client.Session.RSession+<StartHostAsyncBackground>d__104.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Host.Client.Session.RSession+<StartHostAsync>d__103.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Support.Help.IntelliSenseRSession+<StartSessionAsync>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Support.Help.Packages.PackageIndex+<BuildIndexAsync>d__17.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Support.Help.Packages.PackageIndex+<BuildIndexAsync>d__16.MoveNext()
   at Microsoft.Common.Core.TaskExtensions+<>c.<DoNotWaitThreadContinuation>b__6_0(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by AlexanderSher** [comment]
`REvaluationException` can be caused by the same problem we had in package manager session.

**Comment by MikhailArkhipov** [comment]
#3195 related

**Comment by MikhailArkhipov** [comment]
Yes, package index calls `InstalledPackagesFunctionsAsync`. Was this fixed in RC2?

**Comment by AlexanderSher** [comment]
Quite interesting though why we didn't have this issue before. For some reason RHost allows code execution before initialization is actually completed.
@int19h , @karthiknadig  - do you have any ideas?

**Comment by int19h** [comment]
We had the issue of evals executing before initialization was complete before. But it is supposed to be fixed. Perhaps this had regressed?

**Comment by int19h** [comment]
To be specific, look at how `is_r_ready` is set and checked in `host.cpp`. So far as I can tell, the code should still be operating correctly.

Just to be clear, what kind of initialization are we talking about here? The host guarantees that any incoming messages won't be processed until the first R prompt appears (which should only happen when R loaded all the standard packages). If you mean our own initialization code that loads `rtvs` package, then that's supposed to be enforced by `RSession`, right? Neither the host itself, nor the `RHost` wrapper, know anything about it.

**Comment by MikhailArkhipov** [comment]
Package index may be getting `REvaluationException` simply because some package fails to load such as when dependency is missing or something else that makes inspection of the package to fail.

**Comment by AlexanderSher** [comment]
Previously, we allowed evaluation before `IRCallbacks.ReadConsole` is called. Right now, we call `AfterHostStarted` inside `IRCallbacks.ReadConsole`, so it doesn't look like regression on RTVS side.

**Comment by AlexanderSher** [comment]
Here is another error that I've seen in `REvaluationException`:

```
rtvs:::packages.installed()

Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object '.get_standard_repository_db_fields' not found
Calls: <Anonymous> ... packages.installed.named -> installed.packages -> .instPkgFields -> ::: -> get
```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/bd30fdccb5ad88a13db543cf9be4d5150a8152c2
