### ISSUE TITLE
Null reference in VsAppShell.get_ThreadId()

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3259]
From user logs:
```
System.NullReferenceException: Object reference not set to an instance of an object.

at Microsoft.VisualStudio.R.Package.Shell.VsAppShell.get_ThreadId()
at Microsoft.Common.Core.Threading.MainThreadAwaiter.get_IsCompleted()
at Microsoft.R.Components.ConnectionManager.Implementation.ConnectionManager.&lt;CompleteInitializationAsync&gt;d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Common.Core.TaskExtensions.ReThrowTaskException(Object state)
at Microsoft.Common.Core.TaskExtensions.DoNotWait(Task task)
at Microsoft.R.Components.ConnectionManager.Implementation.ConnectionManager..ctor(IStatusBar statusBar, IRSettings settings, IRInteractiveWorkflow interactiveWorkflow)
at Microsoft.R.Components.ConnectionManager.Implementation.ConnectionManagerProvider.CreateConnectionManager(IRInteractiveWorkflow interactiveWorkflow)
at Microsoft.R.Components.InteractiveWorkflow.Implementation.RInteractiveWorkflow..ctor()
at Microsoft.VisualStudio.R.Package.Repl.VsRInteractiveWorkflowProvider.CreateRInteractiveWorkflow()
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at System.Lazy`1.get_Value()
at Microsoft.VisualStudio.R.Package.Repl.VsRInteractiveWorkflowProvider.GetOrCreate()
at Microsoft.VisualStudio.R.Package.Repl.Editor.ReplKeyProcessor.PreviewKeyDown(KeyEventArgs args)
at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c.&lt;DispatchKeyEvents&gt;b__7_1(KeyProcessor p, KeyEventArgs args)
at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c__DisplayClass10_1`1.&lt;Dispatch&gt;b__0()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)</description>
```

**Comment by AlexanderSher** [comment]
What version of RTVS is this?

**Comment by MikhailArkhipov** [comment]
Included in the e-mail thread with the user

**Comment by MikhailArkhipov** [comment]
Since ReplKeyProcessorProvider is MEF-exported, it can be created before the package loads. So VsAppShell is not initialized yet. Options are

a. Load package
b. Init app shell on MainThread accessor
c. Init MainThread separately

**Comment by MikhailArkhipov** [comment]
(d) Just check that package is not loaded and bypass?

**Comment by AlexanderSher** [comment]
I still don't understand how did it happen. `ReplKeyProcessor` is created with REPL window. But to create REPL window instance, you need to call `GetOrCreateVisualComponentAsync` which requires main thread to be initialized.

**Comment by AlexanderSher** [comment]
And `RInteractiveWorkflow` should've been created at this time as well.

**Comment by MikhailArkhipov** [comment]
I think it may actually be a PTVS REPL. Processor is exported for `  [ContentType("Interactive Content")]` which would also match any REPL.

```
    [Export(typeof(IKeyProcessorProvider))]
    [Name(nameof(ReplKeyProcessor))]
    [Order(Before = "Default")]
    [ContentType("Interactive Content")]
    [ContentType(RContentTypeDefinition.ContentType)]
    [TextViewRole(PredefinedTextViewRoles.Interactive)]

```

**Comment by MikhailArkhipov** [comment]
We have attached property
```
interactiveWindow.Properties.AddProperty(typeof(IInteractiveWindowVisualComponent), this);
```
if we attach something similar to the `wpfTextView` itself, we could check if it is R view or not. It may also possible to do

```
var pb = textView.TextBuffer as IProjectionBuffer;
pb.SourceBuffers.Where(b => b.ContentType == R).Any()
```

but I am not 100% if projections are established by the time of the call to the key processor provider

**Comment by AlexanderSher** [comment]
Maybe we just check the language of the input buffer?

**Comment by MikhailArkhipov** [comment]
Top level would be 'projection' for app REPLs. Do you mean `InteractiveWindow.CurrentLanguageBuffer` ?

**Comment by AlexanderSher** [comment]
Yes

**Comment by MikhailArkhipov** [comment]
Sure, if you can get to it from the `KeyProcessorProvider`.

**Comment by MikhailArkhipov** [comment]
```
        [ImportingConstructor]
        public KeyProcessorProvider(IRInteractiveWorkflowProvider provider) {
```
may be a problem. Perhaps we should have default ctor and then find out if the window is R and only then try and fetch `IRInteractiveWorkflowProvider`

**Comment by AlexanderSher** [comment]
Not sure how much of a hack is it, but we can do this:
```
_interactiveWindow = _interactiveWindow ?? _textView.TextBuffer.Properties.PropertyList.FirstOrDefault(kvp => typeof(IInteractiveWindow).IsAssignableFrom(kvp.Key as System.Type));
```

Importing `IRInteractiveWorkflowProvider` isn't a problem by itself, it is `GetOrCreate` that requires UI thread

**Comment by MikhailArkhipov** [comment]
Might be OK for now. As for import, concern was unnecessary instantiation of RTVS objects in a scenario that doesn't need any.

**Comment by AlexanderSher** [comment]
Yeah, `VsRInteractiveWorkflowProvider` has many dependencies.
Ok, I'll change it so that it is accessed through VsAppShell and only after we have checked content type. Have to do it in the `ReplKeyProcessor` itself though.

**Comment by MikhailArkhipov** [comment]
That's fine. We'll be sorting out services access soon.
