### ISSUE TITLE
Brace matcher exception

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3292]
User-reported

```
System.ArgumentException: The point does not belong to a source snapshot of the projection snapshot
at Microsoft.VisualStudio.Text.Projection.Implementation.ElisionSnapshot.MapFromSourceSnapshot(SnapshotPoint point, PositionAffinity affinity)
at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.MapUpToBufferGuts(SnapshotPoint currentPoint, PositionAffinity affinity, Predicate`1 match)
at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.CheckedMapUpToBuffer(SnapshotPoint point, PointTrackingMode trackingMode, Predicate`1 match, PositionAffinity affinity)
at Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.MapUpToBuffer(SnapshotPoint point, PointTrackingMode trackingMode, PositionAffinity affinity, ITextBuffer targetBuffer)
at Microsoft.VisualStudio.Text.Implementation.MappingPoint.GetPoint(ITextBuffer targetBuffer, PositionAffinity affinity)
at Microsoft.VisualStudio.Text.BraceCompletion.Implementation.BraceCompletionManager.IsCaretOnBuffer(ITextBuffer buffer)
at Microsoft.VisualStudio.Text.BraceCompletion.Implementation.BraceCompletionManager.&lt;&gt;c__DisplayClass18_0.&lt;PreTypeChar&gt;b__0()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)</description>


System.InvalidOperationException: Master edit already in progress
at Microsoft.VisualStudio.Text.Implementation.BufferGroup.PerformMasterEdit(ITextBuffer buffer, ISubordinateTextEdit xedit, EditOptions options, Object editTag)
at Microsoft.VisualStudio.Text.Projection.Implementation.ProjectionBuffer.ProjectionEdit.PerformApply()
at Microsoft.VisualStudio.Text.Implementation.BaseBuffer.TextBufferEdit.Apply()
at Microsoft.VisualStudio.Text.Operations.Implementation.EditorOperations.InsertText(String text, Boolean final, String undoText, Boolean isOverwriteModeEnabled)
at Microsoft.VisualStudio.Text.Operations.Implementation.EditorOperations.InsertText(String text)
at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.InsertChar(IntPtr pvaIn, Boolean provisionalText)
at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.Undo.UndoManagerCommandFilter.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.VerticalDetail.VerticalContentCommandFilter.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.Find.FindCommandFilter.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.IntellisenseCommandFilter.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.BraceCompletionCommandFilter.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandFilterWrapper.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandFilterWrapper.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.R.Package.Interop.OleToCommandTargetShim.Invoke(Guid group, Int32 id, Object inputArg, Object&amp; outputArg)
at Microsoft.Markdown.Editor.ContainedLanguage.CommandTargetProxy.Invoke(Guid group, Int32 id, Object inputArg, Object&amp; outputArg)
at Microsoft.Languages.Editor.Controller.Controller.Invoke(Guid group, Int32 id, Object inputArg, Object&amp; outputArg)
at Microsoft.Languages.Editor.Controller.ViewController.Invoke(Guid group, Int32 id, Object inputArg, Object&amp; outputArg)
at Microsoft.Markdown.Editor.Commands.MdMainController.Invoke(Guid group, Int32 id, Object inputArg, Object&amp; outputArg)
at Microsoft.VisualStudio.R.Package.Interop.CommandTargetToOleShim.Exec(Guid&amp; guidCommandGroup, UInt32 commandID, UInt32 commandExecOpt, IntPtr variantIn, IntPtr variantOut)
at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c.&lt;DispatchTextInputEvents&gt;b__6_0(KeyProcessor p, TextCompositionEventArgs args)
at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c__DisplayClass10_1`1.&lt;Dispatch&gt;b__0()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
```

**Comment by red-swan** [comment]
Thanks for opening this. Let me know if I can provide anything to help fix this issue.

**Comment by MikhailArkhipov** [comment]
Anything to narrow down the repro scenario :-) Were you typing braces or, judging from the screenshot, were you typing closing triple tick?

**Comment by MikhailArkhipov** [comment]
Also, what RTVS version is in Help | About?

**Comment by MikhailArkhipov** [comment]
Looks like it specific to R blocks that is unclosed (i.e. missing closing triple tick) and ends at EOF

**Comment by red-swan** [comment]
R Tools for Visual Studio   1.0.30307.1918 RC3

And yes, I was trying to close a triple tick ``` in an rmd code chunk. I've attached the file here. I was writing an introduction to `data.table` for our beginner group here. If you fix the issue, I'll give you the training at no charge. = )


[Markdown1.txt](https://github.com/Microsoft/RTVS/files/839617/Markdown1.txt)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/4e5ef69ffa422dcb50a702da29450be2fbf629ae
