### ISSUE TITLE
Remote R Services error with self-signed certificate

### ISSUE THREAD

**Issue by silentstrikeFIN** [Microsoft/RTVS#3315]
I have installed the R remote service as instructed in the website, and I run into the following error with a self-signed certificate:

R host broker log:

[2017-03-20 15:21:30Z] <Microsoft.AspNetCore.Hosting.Internal.WebHost> (D):
Hosting started

[2017-03-20 15:26:44Z] <Microsoft.AspNetCore.Server.Kestrel> (D):
Connection id "0HL3FIJ0D33OO" started.

[2017-03-20 15:26:45Z] <Microsoft.AspNetCore.Server.Kestrel> (E):
ConnectionFilter.OnConnection
Exception: System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: The server mode SSL must use a certificate with the associated private key.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.<OnConnectionAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NotSupportedException: The server mode SSL must use a certificate with the associated private key.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.<OnConnectionAsync>d__3.MoveNext()<---

[2017-03-20 15:26:45Z] <Microsoft.AspNetCore.Server.Kestrel> (D):
Connection id "0HL3FIJ0D33OO" disconnecting.

[2017-03-20 15:26:45Z] <Microsoft.AspNetCore.Server.Kestrel> (D):
Connection id "0HL3FIJ0D33OO" stopped.

**Comment by MikhailArkhipov** [comment]
Try importing certificate manually (or move it to trusted root). @karthiknadig can provide more details.

**Comment by karthiknadig** [comment]
Follow these steps to generate a self signed certificate:
1.  Download this script: https://gallery.technet.microsoft.com/scriptcenter/Self-signed-certificate-5920a7c6
2.  Run powershell as admin.
3.  Execute: notice the *dot* before .
```
. ./New-SelfSignedCertificateEx.ps1
```
4.  Execute: replace `<server>` with your server's full DNS name. Replace `<password>` with password you want to use.
```
New-SelfSignedCertificateEx -Subject "CN=<server>" -NotBefore 01/01/2011 -NotAfter 01/01/2025 -EKU "Server Authentication" -ProviderName "Microsoft RSA SChannel Cryptographic Provider" -Path C:\my-server-cert.pfx -Password (ConvertTo-SecureString "<password>" -AsPlainText -Force) -Exportable
```
5.  The my-server-cert.pfx should be available in the path provided above.
6.  Import the pfx using **certlm.msc** to Personal store.
7.  Give NETWORK SERVICE permissions to access the imported cert. Right click on the certificate and select All Tasks > Manage private keys and add Network Service.
8.  Restart the server.

**Comment by silentstrikeFIN** [comment]
Tried this without success, but moving the certificate from personal to trusted root fixed the problem. Thank you both.

**Comment by Hong-Revo** [comment]
> Tried this without success, but moving the certificate from personal to trusted root fixed the problem. Thank you both.

This is what I did as well, when I ran into the same problem setting up a remote server. Apparently it shouldn't be necessary, but maybe we should double-check?
