### ISSUE TITLE
Connect to remote R Services (In-Database) 

### ISSUE THREAD

**Issue by tkkasimov** [Microsoft/RTVS#3361]
Can I connect to remote R Services (In-Database) from my notebook with rtools for visual studio? Log Microsoft.R.Host.Broker is below. It seems like R Services (In-Database) from Sql Server 2016 is not supported. Does it so?

[2017-03-29 11:44:12Z] <Microsoft.R.Host.Broker.Startup.Program> (I):
Certificate issued by CN="FQDN"

[2017-03-29 11:44:12Z] <Microsoft.R.Host.Broker.Startup.Program> (I):
Certificate issued to CN="FQDN"

[2017-03-29 11:44:16Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (T):
Auto-detecting R ...

[2017-03-29 11:44:16Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (W):
No compatible R interpreters found

[2017-03-29 11:44:16Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (I):
0 interpreters configured:

[2017-03-29 11:44:16Z] <Microsoft.AspNetCore.Hosting.Internal.WebHost> (D):
Hosting starting

[2017-03-29 11:44:17Z] <Microsoft.AspNetCore.Hosting.Internal.WebHost> (D):
Hosting started

[2017-03-29 11:48:23Z] <Microsoft.AspNetCore.Server.Kestrel> (D):
Connection id "0HL3MG1DQUR4G" started.

[2017-03-29 11:48:23Z] <Microsoft.AspNetCore.Server.Kestrel> (E):
ConnectionFilter.OnConnection
Exception: System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: The server mode SSL must use a certificate with the associated private key.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.<OnConnectionAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NotSupportedException: The server mode SSL must use a certificate with the associated private key.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.<OnConnectionAsync>d__3.MoveNext()<---

**Comment by MikhailArkhipov** [comment]
Have a look here https://github.com/Microsoft/RTVS/issues/3315.
We are also working on ability on providing certificates in files rather than in store (https://github.com/Microsoft/RTVS/issues/3331).

**Comment by MikhailArkhipov** [comment]
Did workaround in #3315 (importing certificate or moving it to the trusted root) work for you?

**Comment by tkkasimov** [comment]
I did all steps, suggested by @karthiknadig and also moved cert to trusted root. But now I'm have the following error:

[2017-04-04 10:19:54Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (T):
Auto-detecting R ...

[2017-04-04 10:19:54Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (W):
No compatible R interpreters found

[2017-04-04 10:19:54Z] <Microsoft.R.Host.Broker.Interpreters.InterpreterManager> (I):
0 interpreters configured:

[2017-04-04 10:19:54Z] <Microsoft.AspNetCore.Hosting.Internal.WebHost> (D):
Hosting starting

[2017-04-04 10:19:55Z] <Microsoft.AspNetCore.Hosting.Internal.WebHost> (D):
Hosting started

[2017-04-04 10:22:54Z] <Microsoft.AspNetCore.Server.Kestrel> (D):
Connection id "0HL3R5DKIC438" started.

[2017-04-04 10:23:00Z] <Microsoft.AspNetCore.Server.Kestrel> (E):
ConnectionFilter.OnConnection
Exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The credentials supplied to the package were not recognized
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.<OnConnectionAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The credentials supplied to the package were not recognized
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.<OnConnectionAsync>d__3.MoveNext()<---

**Comment by karthiknadig** [comment]
Can you check if Network Service has access to the certificate?

**Comment by tkkasimov** [comment]
@karthiknadig thanks, it helped me! I did copy cert back to personal, add permission to Network Service and copy back to trusted root. Now problem looks like so in VS:

Connecting to R Workspace failed.
Reason: No R interpreters installed

But I have the R Services (In-Database) from Sql Server 2016 installed

**Comment by MikhailArkhipov** [comment]
Due to the way SQL installs R it is sometimes difficult to locate. However, you can configure intepreters manually in the broker config file. 

In `Microsoft.R.Host.Broker.json`

```
“R” {
  “AutoDetect”: true,
  “Interpreters”: {
    “Key1”: {
       “Name1”: “BasePath1”
    },
    “Key2”: {
       “Name2”: “BasePath2”
    },
    …
}
```

`AutoDetect` is the default setting and can be omitted. `Key1`, `Key2` etc is what’ll go after # in the URL. `Name` is supposed to be descriptive.

**Comment by tkkasimov** [comment]
Thanks, it helped!
