### ISSUE TITLE
RTVS crashes when loading breast cancer NKI dataset into global environment in R interactive

### ISSUE THREAD

**Issue by Schmitzi** [Microsoft/RTVS#3606]
Required packages:
* Biobase (https://bioconductor.org/packages/release/bioc/html/Biobase.html)
* breastCancerNKI (http://bioconductor.org/packages/release/data/experiment/html/breastCancerNKI.html)

Installed R version: Microsoft R Open 3.3.3

To reproduce open R interactive and type:
```r
library(Biobase)
library(breastCancerNKI)
data(nki)
```
After a few seconds Visual Studio will stop working and the following event will show up in the Windows Event Viewer:
```
Level	Date and Time	Source	Event ID	Task Category
Error	2017-06-07 15:38:28	.NET Runtime	1026	None	Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException
   at Newtonsoft.Json.Linq.Extensions.Convert[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon)
   at Newtonsoft.Json.Linq.JToken.Value[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object)
   at Microsoft.R.DataInspection.RValueInfo..ctor(Microsoft.R.Host.Client.IRExpressionEvaluator, System.String, System.String, System.String, Newtonsoft.Json.Linq.JObject)
   at Microsoft.R.DataInspection.REvaluationResultInfo.Parse(Microsoft.R.Host.Client.IRExpressionEvaluator, System.String, System.String, Newtonsoft.Json.Linq.JObject)
   at Microsoft.R.DataInspection.RSessionExtensions+<DescribeChildrenAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Editor.Data.RSessionDataObject+<GetChildrenAsyncInternal>d__21.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.R.Package.DataInspect.WorkspaceVariableProvider+<UpdateList>d__12.MoveNext()
   at Microsoft.Common.Core.TaskExtensions+<>c.<DoNotWaitThreadContinuation>b__6_0(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
The exception occurs when loading the data in a script, too. No crash occurs when loading the dataset in an R session hosted in powershell/cmd or Rstudio.

**Comment by MikhailArkhipov** [comment]
@int19h could you have a look. We can include fix in 2017 15.3

**Comment by MikhailArkhipov** [comment]
@Schmitzi - are you using 2015 or 2017?

**Comment by Schmitzi** [comment]
I am using Visual Studio 2017 Community.

**Comment by int19h** [comment]
The problem is that `dim()` function, when invoked on this object, returns a vector with named elements. We then serialize the result directly to JSON, on the assumption that it's always unnamed (and therefore will serialize as array) - but in this case it gets serialized as object instead.

The fix is to remove `names()` before serializing.

**Comment by MikhailArkhipov** [comment]
@Schmitzi - until VS update is released, you can take
`https://github.com/Microsoft/RTVS/blob/Release/1_0/src/Host/Client/Impl/rtvs/R/eval.R`
and replace existing file in 
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\R Tools...\rtvs\R`
