### ISSUE TITLE
Test threading issues

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3744]
ExportAsPdf, SourceRScriptTest

```
Test Name:	RPlotIntegrationTest.ExportAsPdf
Test FullName:	Microsoft.R.Components.Test.Plots.RPlotIntegrationTest.ExportAsPdf (04d0a463e39144fb9c77612b8c176449b61109b8)
Test Source:	F:\RTVS\src\Windows\R\Components\Test\Plots\RPlotIntegrationTest.cs : line 486
Test Outcome:	Failed
Test Duration:	0:00:23.483

Result1 Name:	RPlotIntegrationTest.ExportAsPdf
Result1 Outcome:	Failed
Result1 Duration:	0:00:00.001
Result1 StackTrace:	
at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.UIElement.set_Visibility(Visibility value)
   at Microsoft.R.Components.Test.Fakes.VisualComponentFactories.Container`1.Show(Boolean focus, Boolean immediate) in F:\RTVS\src\Windows\R\Components\Test\Fakes\VisualComponentFactories\Container.cs:line 27
   at Microsoft.R.Components.InteractiveWorkflow.Implementation.InteractiveWindowConsole.<WriteAsync>d__7.MoveNext() in F:\RTVS\src\Windows\R\Components\Impl\InteractiveWorkflow\Implementation\InteractiveWindowConsole.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.UnitTests.Core.XUnit.TestMethodRunner.<RunAsync>d__15.MoveNext() in F:\RTVS\src\UnitTests\Core\Impl\XUnit\TestMethodRunner.cs:line 162
Result1 Message:	System.InvalidOperationException : The calling thread cannot access this object because a different thread owns it.
Result1 StandardOutput:
Result1 StandardError:

```

**Comment by MikhailArkhipov** [comment]
Passes now

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/30b7dcc86b562c3678d27ea21130cbbb4c34a3b8
