### ISSUE TITLE
Closing VS throws: Connection point was not released

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3767]
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Connection point was not released. Interface Microsoft.VisualStudio.TextManager.Interop.IVsTextManagerEvents4, 
Call stack: 
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Microsoft.VisualStudio.R.Package.Interop.ConnectionPointCookie..ctor(Object source, Object sink, Type eventInterface, Boolean throwException)
   at Microsoft.VisualStudio.R.Package.Interop.ConnectionPointCookie..ctor(Object source, Object sink, Type eventInterface)
   at Microsoft.VisualStudio.R.Package.Editors.LanguageSettingsStorage..ctor(IVsPackage package, IServiceContainer services, Guid languageServiceId, IEnumerable`1 automationObjectNames)
   at Microsoft.VisualStudio.R.Packages.R.RPackage.LoadEditorSettings()
   at Microsoft.VisualStudio.R.Packages.R.RPackage.Initialize()
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)
   at Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid& packageGuid, Int32 reason, Guid& context)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetPackage()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.EnsureContentConstructed()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.PreloadOnScreenContent(View view)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.set_FrameView(View value)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.ConnectViewToFrame(View shownView)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.viewManager_WindowProfileChanging(Object sender, WindowProfileChangingEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.VisualStudio.PlatformUI.ExtensionMethods.RaiseEvent[TEventArgs](EventHandler`1 eventHandler, Object source, TEventArgs args)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewManager.set_WindowProfile(WindowProfile value)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.set_ActiveProfile(WindowProfile value)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.<>c__DisplayClass171_0.<LoadFrameLayout>b__0()
   at Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(Func`1 method, Boolean reportError, Boolean setShellErrorInfo)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.LoadFrameLayout(String szLayoutName, String szLayoutMode, String szLayoutSubMode, String szAlternatePath)
   at Microsoft.VisualStudio.R.Package.Interop.ConnectionPointCookie.Finalize()
```

**Comment by MikhailArkhipov** [comment]
Mostly harmless

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/ea512475a4f87015c7a49fe2ab94f42f2b05f4ee
