### ISSUE TITLE
Switching from remote to local occasionally throws 404 Not found.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3821]
Response status code does not indicate success: 404 (Not Found).
```
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.R.Host.Client.BrokerServices.WebService.EnsureSuccessStatusCode(HttpResponseMessage response)
   at Microsoft.R.Host.Client.BrokerServices.WebService.<>c__DisplayClass14_0.<<HttpDeleteAsync>b__0>d.MoveNext()
```

**Comment by karthiknadig** [comment]
This is when we send HTTP request DELETE to Broker.
