### ISSUE TITLE
Add R Script after creating a new folder in the project throws directory not found exception

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3895]
```
System.IO.DirectoryNotFoundException occurred
  HResult=0x80070003
  Message=Could not find a part of the path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ItemTemplates\R\rscript\rscript.vstemplate'.
  Source=mscorlib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.RunWizard(SimpleHierarchyNode parentNode, String itemName, String wizardToRun, IntPtr dlgOwner)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<AddItemWithSpecificAsync>d__602.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.<>c__DisplayClass1_0.<<AddFromTemplate>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.<>c__DisplayClass68_0`1.<<Mutate>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass560_0.<<Mutate>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.Mutate(Func`1 asyncAction, Boolean includesFileSystemChange)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.Mutate[T](Func`1 asyncAction, Boolean includesFileSystemChange)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.AddFromTemplate(String fileName, String name)
   at Microsoft.VisualStudio.R.Package.ProjectSystem.ProjectSystemServices.AddNewItem(String templateName, String name, String extension, String destinationPath) in G:\GIT\RTVS\src\Package\Impl\ProjectSystem\ProjectSystemServices.cs:line 106
   at Microsoft.VisualStudio.R.Package.ProjectSystem.Commands.AddItemCommand.TryHandleCommand(IImmutableSet`1 nodes, Int64 commandId, Boolean focused, Int64 commandExecuteOptions, IntPtr variantArgIn, IntPtr variantArgOut) in G:\GIT\RTVS\src\Package\Impl\ProjectSystem\Commands\AddItemCommand.cs:line 38
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<InternalExecCommandAsync>d__680.MoveNext()
```

**Comment by karthiknadig** [comment]
This is under F5

**Comment by MikhailArkhipov** [comment]
Yes, F5-specific. Setup deploys templates differently.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/235d2372fc802648005bd71d2291feaf7c2f84f4
