### ISSUE TITLE
Copy pasting from REPL to editor sometimes throws 'length is not valid'

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3896]
```
System.ArgumentException occurred
  HResult=0x80070057
  Message=length is not valid
  Source=Microsoft.R.Common.Core
  StackTrace:
   at Microsoft.Common.Core.Diagnostics.Check.Argument(String argumentName, Func`1 predicate) in G:\GIT\RTVS\src\Common\Core\Impl\Diagnostics\Check.cs:line 43
   at Microsoft.Languages.Core.Text.TextRange..ctor(Int32 start, Int32 length) in G:\GIT\RTVS\src\Languages\Core\Impl\Text\TextRange.cs:line 47
   at Microsoft.Languages.Core.Text.TextRange.FromBounds(Int32 start, Int32 end) in G:\GIT\RTVS\src\Languages\Core\Impl\Text\TextRange.cs:line 76
   at Microsoft.R.Editor.Formatting.RangeFormatter.FormatRange(IEditorView editorView, IEditorBuffer editorBuffer, ITextRange formatRange) in G:\GIT\RTVS\src\R\Editor\Impl\Formatting\RangeFormatter.cs:line 77
   at Microsoft.R.Editor.Formatting.FormatOnPasteCommand.Invoke(Guid group, Int32 id, Object inputArg, Object& outputArg) in G:\GIT\RTVS\src\Windows\R\Editor\Impl\Formatting\FormatOnPasteCommand.cs:line 81
   at Microsoft.Common.Core.UI.Commands.Controller.Invoke(Guid group, Int32 id, Object inputArg, Object& outputArg) in G:\GIT\RTVS\src\Common\Core\Impl\UI\Commands\Controller.cs:line 44
   at Microsoft.Languages.Editor.Controllers.ViewController.Invoke(Guid group, Int32 id, Object inputArg, Object& outputArg) in G:\GIT\RTVS\src\Windows\Editor\Impl\Controllers\ViewController.cs:line 101
   at Microsoft.VisualStudio.R.Package.Interop.CommandTargetToOleShim.Exec(Guid& guidCommandGroup, UInt32 commandID, UInt32 commandExecOpt, IntPtr variantIn, IntPtr variantOut) in G:\GIT\RTVS\src\Package\Impl\Interop\CommandTargetToOleShim.cs:line 59
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)

```

**Comment by MikhailArkhipov** [comment]
Did you merge master?

**Comment by karthiknadig** [comment]
Did not repro after merging with main.
