### ISSUE TITLE
NRE while sourcing file to remote.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3930]
```
"Object reference not set to an instance of an object."
   at Microsoft.Languages.Editor.BraceMatch.BraceHighlighter.get_BraceMatcher()
   at Microsoft.Languages.Editor.BraceMatch.BraceHighlighter.<GetTags>d__17.MoveNext()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__39.MoveNext()
```

**Comment by MikhailArkhipov** [comment]
Do you have the file you've sourced?

**Comment by karthiknadig** [comment]
[Script.zip](https://github.com/Microsoft/RTVS/files/1281930/Script.zip)

**Comment by MikhailArkhipov** [comment]
Should be fixed by https://github.com/Microsoft/RTVS/commit/0d85013d0506dfd058522251fde8439fd70e5c5e, accidentally pushed directly apparently
