### ISSUE TITLE
Select all in a R file throw ArgumentOutOfRange

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3950]
This causes a VS Crash.
```
System.ArgumentOutOfRangeException occurred
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values.
Parameter name: position
  Source=Microsoft.VisualStudio.Text.Data
  StackTrace:
   at Microsoft.VisualStudio.Text.SnapshotPoint..ctor(ITextSnapshot snapshot, Int32 position)
   at Microsoft.VisualStudio.Text.SnapshotPoint.op_Addition(SnapshotPoint point, Int32 offset)
   at Microsoft.R.Editor.SuggestedActions.RSuggestedActionsSource.PositionFromRange(SnapshotSpan range) in G:\GIT\RTVS\src\Windows\R\Editor\Impl\SuggestedActions\RSuggestedActionsSource.cs:line 104
   at Microsoft.R.Editor.SuggestedActions.RSuggestedActionsSource.<>c__DisplayClass9_0.<HasSuggestedActionsAsync>b__0(ISuggestedActionProvider a) in G:\GIT\RTVS\src\Windows\R\Editor\Impl\SuggestedActions\RSuggestedActionsSource.cs:line 88
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.R.Editor.SuggestedActions.RSuggestedActionsSource.HasSuggestedActionsAsync(ISuggestedActionCategorySet requestedActionCategories, SnapshotSpan range, CancellationToken cancellationToken) in G:\GIT\RTVS\src\Windows\R\Editor\Impl\SuggestedActions\RSuggestedActionsSource.cs:line 86
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbBroker.<>c__DisplayClass28_0.<<GetSuggestedActionCategoriesAsync>b__0>d.MoveNext()

```

**Comment by MikhailArkhipov** [comment]
Need specific file. Does not repro on Ctrl+A of Shift-Mouse

**Comment by MikhailArkhipov** [comment]
Specific to the very end of the file position.

**Comment by MikhailArkhipov** [comment]
Should be fixed by https://github.com/Microsoft/RTVS/commit/0d85013d0506dfd058522251fde8439fd70e5c5e, accidentally pushed directly apparently
