### ISSUE TITLE
NRE upon rightclick in a R file

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3951]
```
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.R.Editor
  StackTrace:
   at Microsoft.R.Editor.SmartIndent.SmartIndenter.GetDesiredIndentation(IEditorLine line) in G:\GIT\RTVS\src\R\Editor\Impl\SmartIndent\SmartIndenter.cs:line 36
   at Microsoft.R.Editor.SmartIndent.SmartIndent.GetDesiredIndentation(ITextSnapshotLine line) in G:\GIT\RTVS\src\Windows\R\Editor\Impl\SmartIndent\SmartIndent.cs:line 19
   at Microsoft.VisualStudio.Text.Editor.Implementation.SmartIndentationService.GetDesiredIndentation(ITextView textView, ITextSnapshotLine line)
   at Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.MapXCoordinate(ITextViewLine textLine, Double xCoordinate, Boolean userSpecifiedXCoordinate)
   at Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.MoveTo(ITextViewLine textLine, Double xCoordinate, Boolean captureHorizontalPosition)
   at Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.MoveTo(ITextViewLine textLine, Double xCoordinate)
   at Microsoft.VisualStudio.Editor.Implementation.VsMouseProcessor.MoveCaretToPosition(Point mousePosition)
   at Microsoft.VisualStudio.Editor.Implementation.VsMouseProcessor.HandlePreprocessRightButtonDown(InputEventArgs e)
   at Microsoft.VisualStudio.Editor.Implementation.VsMouseProcessor.PreprocessMouseRightButtonDown(MouseButtonEventArgs e)
   at Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor.<>c__DisplayClass42_0.<UIElement_MouseRightButtonDown>b__0(IMouseProcessor p)
   at Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor.<>c__DisplayClass56_1.<MouseProcessorHandler>b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
```

**Comment by MikhailArkhipov** [comment]
OK, this should be fixed by the references revert
