### ISSUE TITLE
Exception in run loop, close VS while running shiny app.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3953]
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Exception in RHost run loop:
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.get_Token()
   at Microsoft.Common.Core.Disposables.DisposeToken.get_CancellationToken()
   at Microsoft.R.Components.InteractiveWorkflow.Implementation.InteractiveWindowConsole.<WriteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Common.Core.TaskExtensions.ReThrowTaskException(Object state)
   at Microsoft.Common.Core.TaskExtensions.DoNotWait(Task task)
   at Microsoft.R.Components.InteractiveWorkflow.Implementation.InteractiveWindowConsole.WriteError(String text)
   at Microsoft.R.Components.InteractiveWorkflow.Implementation.InteractiveWindowConsole.WriteErrorLine(String text)
   at Microsoft.R.Components.InteractiveWorkflow.Impl......
<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by MikhailArkhipov** [comment]
May need this in `Release/1_2`

**Comment by karthiknadig** [comment]
This does not need to be shiny. As long as there is a busy host. I hit this issue when i tried to close VS with package manager open and loading.
