### ISSUE TITLE
VS crashes if docker is stopped while Vs is running.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#4034]
Repro steps:
1. Start docker for windows
2. Start VS 2017
3. Open containers, VS shows "create" container button.
4. Quit docker for windows

```
Microsoft.R.Containers.ContainerException occurred
  HResult=0x80131500
  Message=Error response from daemon: Bad response from Docker engine

  Source=Microsoft.R.Containers
  StackTrace:
   at Microsoft.R.Containers.Docker.LocalDockerService.<ExecuteCommandAsync>d__27.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.R.Containers.Docker.LocalDockerService.<ListContainersAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.R.Components.Containers.Implementation.ContainerManager.<UpdateContainersOnceAsync>d__28.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.R.Components.Containers.Implementation.ContainerManager.<UpdateContainersAsync>d__27.MoveNext()
   at Microsoft.Common.Core.TaskExtensions.ReThrowTaskException(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by AlexanderSher** [comment]
Ok, so should it throw `ContainerException` or `ContainerServiceNotRunningException`?

**Comment by karthiknadig** [comment]
I think `ContainerException`. There are a bunch of cases where it is hard to say the error was because the daemon was not running or because there was an issue with the pipe. In this case, if we try to just detect the process, it might have said that the process is running. The error above occurred while the docker for windows daemon was shutting down.

**Comment by AlexanderSher** [comment]
Does it mean that we need a third message for the watermark (in addition to "not installed" and "not running")?
