### ISSUE TITLE
Exception while running shiny app

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#4047]
Exception stack:
```
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.VisualStudio.R.Package.Help.HelpVisualComponent.IsHelpUrl(String url)
   at Microsoft.VisualStudio.R.Package.Help.HelpVisualComponent.Navigate(String url)
   at Microsoft.R.Components.InteractiveWorkflow.Implementation.RSessionCallback.<ShowHelpAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.R.Host.Client.Session.RSession.<Microsoft-R-Host-Client-IRCallbacks-WebBrowser>d__142.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Common.Core.TaskExtensions.<>c.<DoNotWaitThreadContinuation>b__6_0(Object s)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
Repro:
```
library(plotGoogleMaps)
library(shiny)

ui = pageWithSidebar(
    headerPanel('Map'),
    sidebarPanel(""),
    mainPanel(uiOutput('mymap'))
  )
server = function(input, output) {

    output$mymap <- renderUI({
        data(meuse)
        coordinates(meuse) = ~x + y
        proj4string(meuse) <- CRS("+init=epsg:28992")
        m <- plotGoogleMaps(meuse, filename = 'myMap1.html', iconMarker = 'wind_turbine.png', openMap = T, mapTypeId = 'TERRAIN')

        tags$iframe(
        srcdoc = paste(readLines('myMap1.html'), collapse = '\n'),
        width = "100%",
        height = "600px"
      )
    })

}

shinyApp(ui, server)

```

**Comment by MikhailArkhipov** [comment]
So what does it pass as URL?

**Comment by karthiknadig** [comment]
"myMap1.html". The webBrowser message gets called twice, first time it is for the shiny server. The second time it is for the file that was created at "~/myMap1.html".
