### ISSUE TITLE
Failed to connect to remote R server 

### ISSUE THREAD

**Issue by SQLServerDBA1986** [Microsoft/RTVS#4355]
Users are unable to connect from Visual studio 2015 to R Server. Version of R interpreter: Microsoft R open 3.5.1. I have a certificate and Network services has access to it. I would appreciate it if anyone can help please. Thanks. 
here is the error in R host broker log

[2019-01-25 14:01:29Z] <HttpsConnectionFilter> (I):
Failed to authenticate HTTPS connection.
Exception: System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.<OnConnectionAsync>d__6.MoveNext()

**Comment by SQLServerDBA1986** [comment]
users tried again, by putting the fully qualified name of the server when trying to connect to R , I get different errors in the log:

[2019-01-25 14:28:12Z] <Microsoft.AspNetCore.Builder.RouterMiddleware> (D):
Request did not match any routes.

[2019-01-25 14:28:12Z] <Odachi.AspNetCore.Authentication.Basic.BasicMiddleware> (I):
Basic was not authenticated. Failure message: No authorization header.

[2019-01-25 14:28:12Z] <Odachi.AspNetCore.Authentication.Basic.BasicMiddleware> (I):
AuthenticationScheme: Basic was challenged.

[2019-01-25 14:28:12Z] <Microsoft.AspNetCore.Server.Kestrel> (D):
Connection id "0HLK2PMDA55M1" completed keep alive response.

[2019-01-25 14:28:12Z] <Microsoft.AspNetCore.Hosting.Internal.WebHost> (I):
Request finished in 28.0974ms 401
