### ISSUE TITLE
Websocket error displayed in output during graphics device test

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#471]
Any test in IdeGraphicsDeviceTest or XamlGraphicsDeviceTest can be used to repro.  Check the test result output and you'll see:

```
Test Name:	MultiplePlotsNoSleep
Test Outcome:	Passed
Result StandardOutput:	12/4/2015 2:07:06 PM|Fatal|WebSocket.processException|WebSocketSharp.WebSocketException: The header part of a frame cannot be read from the data source.
                              at WebSocketSharp.WebSocketFrame.<>c__DisplayClass7.<ReadAsync>b__6(Byte[] header)
                              at WebSocketSharp.Ext.<>c__DisplayClass6.<ReadBytesAsync>b__5(IAsyncResult ar)
```

**Comment by jflam** [comment]
No repro
